#pragma once
#ifndef SRC_EXTRAS_KBOOKMARKSC_LIBKBOOKMARKCONTEXTMENU_H
#define SRC_EXTRAS_KBOOKMARKSC_LIBKBOOKMARKCONTEXTMENU_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KBookmark KBookmark;
typedef struct KBookmarkContextMenu KBookmarkContextMenu;
typedef struct KBookmarkManager KBookmarkManager;
typedef struct KBookmarkOwner KBookmarkOwner;
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMenu QMenu;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionMenuItem QStyleOptionMenuItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KBookmarkContextMenu* KBookmarkContextMenu_new(const KBookmark* bm, KBookmarkManager* manager, KBookmarkOwner* owner);
KBookmarkContextMenu* KBookmarkContextMenu_new2(const KBookmark* bm, KBookmarkManager* manager, KBookmarkOwner* owner, QWidget* parent);
QMetaObject* KBookmarkContextMenu_MetaObject(const KBookmarkContextMenu* self);
void* KBookmarkContextMenu_Metacast(KBookmarkContextMenu* self, const char* param1);
int KBookmarkContextMenu_Metacall(KBookmarkContextMenu* self, int param1, int param2, void** param3);
libqt_string KBookmarkContextMenu_Tr(const char* s);
void KBookmarkContextMenu_AddActions(KBookmarkContextMenu* self);
void KBookmarkContextMenu_SetBrowserMode(KBookmarkContextMenu* self, bool browserMode);
bool KBookmarkContextMenu_BrowserMode(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_SlotEditAt(KBookmarkContextMenu* self);
void KBookmarkContextMenu_SlotProperties(KBookmarkContextMenu* self);
void KBookmarkContextMenu_SlotInsert(KBookmarkContextMenu* self);
void KBookmarkContextMenu_SlotRemove(KBookmarkContextMenu* self);
void KBookmarkContextMenu_SlotCopyLocation(KBookmarkContextMenu* self);
void KBookmarkContextMenu_SlotOpenFolderInTabs(KBookmarkContextMenu* self);
libqt_string KBookmarkContextMenu_Tr2(const char* s, const char* c);
libqt_string KBookmarkContextMenu_Tr3(const char* s, const char* c, int n);
void KBookmarkContextMenu_OnMetacall(KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseMetacall(KBookmarkContextMenu* self, int param1, int param2, void** param3);
void KBookmarkContextMenu_OnAddActions(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseAddActions(KBookmarkContextMenu* self);
QSize* KBookmarkContextMenu_SizeHint(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnSizeHint(const KBookmarkContextMenu* self, intptr_t slot);
QSize* KBookmarkContextMenu_QBaseSizeHint(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_ChangeEvent(KBookmarkContextMenu* self, QEvent* param1);
void KBookmarkContextMenu_OnChangeEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseChangeEvent(KBookmarkContextMenu* self, QEvent* param1);
void KBookmarkContextMenu_KeyPressEvent(KBookmarkContextMenu* self, QKeyEvent* param1);
void KBookmarkContextMenu_OnKeyPressEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseKeyPressEvent(KBookmarkContextMenu* self, QKeyEvent* param1);
void KBookmarkContextMenu_MouseReleaseEvent(KBookmarkContextMenu* self, QMouseEvent* param1);
void KBookmarkContextMenu_OnMouseReleaseEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseMouseReleaseEvent(KBookmarkContextMenu* self, QMouseEvent* param1);
void KBookmarkContextMenu_MousePressEvent(KBookmarkContextMenu* self, QMouseEvent* param1);
void KBookmarkContextMenu_OnMousePressEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseMousePressEvent(KBookmarkContextMenu* self, QMouseEvent* param1);
void KBookmarkContextMenu_MouseMoveEvent(KBookmarkContextMenu* self, QMouseEvent* param1);
void KBookmarkContextMenu_OnMouseMoveEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseMouseMoveEvent(KBookmarkContextMenu* self, QMouseEvent* param1);
void KBookmarkContextMenu_WheelEvent(KBookmarkContextMenu* self, QWheelEvent* param1);
void KBookmarkContextMenu_OnWheelEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseWheelEvent(KBookmarkContextMenu* self, QWheelEvent* param1);
void KBookmarkContextMenu_EnterEvent(KBookmarkContextMenu* self, QEnterEvent* param1);
void KBookmarkContextMenu_OnEnterEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseEnterEvent(KBookmarkContextMenu* self, QEnterEvent* param1);
void KBookmarkContextMenu_LeaveEvent(KBookmarkContextMenu* self, QEvent* param1);
void KBookmarkContextMenu_OnLeaveEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseLeaveEvent(KBookmarkContextMenu* self, QEvent* param1);
void KBookmarkContextMenu_HideEvent(KBookmarkContextMenu* self, QHideEvent* param1);
void KBookmarkContextMenu_OnHideEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseHideEvent(KBookmarkContextMenu* self, QHideEvent* param1);
void KBookmarkContextMenu_PaintEvent(KBookmarkContextMenu* self, QPaintEvent* param1);
void KBookmarkContextMenu_OnPaintEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBasePaintEvent(KBookmarkContextMenu* self, QPaintEvent* param1);
void KBookmarkContextMenu_ActionEvent(KBookmarkContextMenu* self, QActionEvent* param1);
void KBookmarkContextMenu_OnActionEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseActionEvent(KBookmarkContextMenu* self, QActionEvent* param1);
void KBookmarkContextMenu_TimerEvent(KBookmarkContextMenu* self, QTimerEvent* param1);
void KBookmarkContextMenu_OnTimerEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseTimerEvent(KBookmarkContextMenu* self, QTimerEvent* param1);
bool KBookmarkContextMenu_Event(KBookmarkContextMenu* self, QEvent* param1);
void KBookmarkContextMenu_OnEvent(KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseEvent(KBookmarkContextMenu* self, QEvent* param1);
bool KBookmarkContextMenu_FocusNextPrevChild(KBookmarkContextMenu* self, bool next);
void KBookmarkContextMenu_OnFocusNextPrevChild(KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseFocusNextPrevChild(KBookmarkContextMenu* self, bool next);
void KBookmarkContextMenu_InitStyleOption(const KBookmarkContextMenu* self, QStyleOptionMenuItem* option, const QAction* action);
void KBookmarkContextMenu_OnInitStyleOption(const KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseInitStyleOption(const KBookmarkContextMenu* self, QStyleOptionMenuItem* option, const QAction* action);
int KBookmarkContextMenu_DevType(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnDevType(const KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseDevType(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_SetVisible(KBookmarkContextMenu* self, bool visible);
void KBookmarkContextMenu_OnSetVisible(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseSetVisible(KBookmarkContextMenu* self, bool visible);
QSize* KBookmarkContextMenu_MinimumSizeHint(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnMinimumSizeHint(const KBookmarkContextMenu* self, intptr_t slot);
QSize* KBookmarkContextMenu_QBaseMinimumSizeHint(const KBookmarkContextMenu* self);
int KBookmarkContextMenu_HeightForWidth(const KBookmarkContextMenu* self, int param1);
void KBookmarkContextMenu_OnHeightForWidth(const KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseHeightForWidth(const KBookmarkContextMenu* self, int param1);
bool KBookmarkContextMenu_HasHeightForWidth(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnHasHeightForWidth(const KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseHasHeightForWidth(const KBookmarkContextMenu* self);
QPaintEngine* KBookmarkContextMenu_PaintEngine(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnPaintEngine(const KBookmarkContextMenu* self, intptr_t slot);
QPaintEngine* KBookmarkContextMenu_QBasePaintEngine(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_MouseDoubleClickEvent(KBookmarkContextMenu* self, QMouseEvent* event);
void KBookmarkContextMenu_OnMouseDoubleClickEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseMouseDoubleClickEvent(KBookmarkContextMenu* self, QMouseEvent* event);
void KBookmarkContextMenu_KeyReleaseEvent(KBookmarkContextMenu* self, QKeyEvent* event);
void KBookmarkContextMenu_OnKeyReleaseEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseKeyReleaseEvent(KBookmarkContextMenu* self, QKeyEvent* event);
void KBookmarkContextMenu_FocusInEvent(KBookmarkContextMenu* self, QFocusEvent* event);
void KBookmarkContextMenu_OnFocusInEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseFocusInEvent(KBookmarkContextMenu* self, QFocusEvent* event);
void KBookmarkContextMenu_FocusOutEvent(KBookmarkContextMenu* self, QFocusEvent* event);
void KBookmarkContextMenu_OnFocusOutEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseFocusOutEvent(KBookmarkContextMenu* self, QFocusEvent* event);
void KBookmarkContextMenu_MoveEvent(KBookmarkContextMenu* self, QMoveEvent* event);
void KBookmarkContextMenu_OnMoveEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseMoveEvent(KBookmarkContextMenu* self, QMoveEvent* event);
void KBookmarkContextMenu_ResizeEvent(KBookmarkContextMenu* self, QResizeEvent* event);
void KBookmarkContextMenu_OnResizeEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseResizeEvent(KBookmarkContextMenu* self, QResizeEvent* event);
void KBookmarkContextMenu_CloseEvent(KBookmarkContextMenu* self, QCloseEvent* event);
void KBookmarkContextMenu_OnCloseEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseCloseEvent(KBookmarkContextMenu* self, QCloseEvent* event);
void KBookmarkContextMenu_ContextMenuEvent(KBookmarkContextMenu* self, QContextMenuEvent* event);
void KBookmarkContextMenu_OnContextMenuEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseContextMenuEvent(KBookmarkContextMenu* self, QContextMenuEvent* event);
void KBookmarkContextMenu_TabletEvent(KBookmarkContextMenu* self, QTabletEvent* event);
void KBookmarkContextMenu_OnTabletEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseTabletEvent(KBookmarkContextMenu* self, QTabletEvent* event);
void KBookmarkContextMenu_DragEnterEvent(KBookmarkContextMenu* self, QDragEnterEvent* event);
void KBookmarkContextMenu_OnDragEnterEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseDragEnterEvent(KBookmarkContextMenu* self, QDragEnterEvent* event);
void KBookmarkContextMenu_DragMoveEvent(KBookmarkContextMenu* self, QDragMoveEvent* event);
void KBookmarkContextMenu_OnDragMoveEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseDragMoveEvent(KBookmarkContextMenu* self, QDragMoveEvent* event);
void KBookmarkContextMenu_DragLeaveEvent(KBookmarkContextMenu* self, QDragLeaveEvent* event);
void KBookmarkContextMenu_OnDragLeaveEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseDragLeaveEvent(KBookmarkContextMenu* self, QDragLeaveEvent* event);
void KBookmarkContextMenu_DropEvent(KBookmarkContextMenu* self, QDropEvent* event);
void KBookmarkContextMenu_OnDropEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseDropEvent(KBookmarkContextMenu* self, QDropEvent* event);
void KBookmarkContextMenu_ShowEvent(KBookmarkContextMenu* self, QShowEvent* event);
void KBookmarkContextMenu_OnShowEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseShowEvent(KBookmarkContextMenu* self, QShowEvent* event);
bool KBookmarkContextMenu_NativeEvent(KBookmarkContextMenu* self, const libqt_string eventType, void* message, intptr_t* result);
void KBookmarkContextMenu_OnNativeEvent(KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseNativeEvent(KBookmarkContextMenu* self, const libqt_string eventType, void* message, intptr_t* result);
int KBookmarkContextMenu_Metric(const KBookmarkContextMenu* self, int param1);
void KBookmarkContextMenu_OnMetric(const KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseMetric(const KBookmarkContextMenu* self, int param1);
void KBookmarkContextMenu_InitPainter(const KBookmarkContextMenu* self, QPainter* painter);
void KBookmarkContextMenu_OnInitPainter(const KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseInitPainter(const KBookmarkContextMenu* self, QPainter* painter);
QPaintDevice* KBookmarkContextMenu_Redirected(const KBookmarkContextMenu* self, QPoint* offset);
void KBookmarkContextMenu_OnRedirected(const KBookmarkContextMenu* self, intptr_t slot);
QPaintDevice* KBookmarkContextMenu_QBaseRedirected(const KBookmarkContextMenu* self, QPoint* offset);
QPainter* KBookmarkContextMenu_SharedPainter(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnSharedPainter(const KBookmarkContextMenu* self, intptr_t slot);
QPainter* KBookmarkContextMenu_QBaseSharedPainter(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_InputMethodEvent(KBookmarkContextMenu* self, QInputMethodEvent* param1);
void KBookmarkContextMenu_OnInputMethodEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseInputMethodEvent(KBookmarkContextMenu* self, QInputMethodEvent* param1);
QVariant* KBookmarkContextMenu_InputMethodQuery(const KBookmarkContextMenu* self, int param1);
void KBookmarkContextMenu_OnInputMethodQuery(const KBookmarkContextMenu* self, intptr_t slot);
QVariant* KBookmarkContextMenu_QBaseInputMethodQuery(const KBookmarkContextMenu* self, int param1);
bool KBookmarkContextMenu_EventFilter(KBookmarkContextMenu* self, QObject* watched, QEvent* event);
void KBookmarkContextMenu_OnEventFilter(KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseEventFilter(KBookmarkContextMenu* self, QObject* watched, QEvent* event);
void KBookmarkContextMenu_ChildEvent(KBookmarkContextMenu* self, QChildEvent* event);
void KBookmarkContextMenu_OnChildEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseChildEvent(KBookmarkContextMenu* self, QChildEvent* event);
void KBookmarkContextMenu_CustomEvent(KBookmarkContextMenu* self, QEvent* event);
void KBookmarkContextMenu_OnCustomEvent(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseCustomEvent(KBookmarkContextMenu* self, QEvent* event);
void KBookmarkContextMenu_ConnectNotify(KBookmarkContextMenu* self, const QMetaMethod* signal);
void KBookmarkContextMenu_OnConnectNotify(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseConnectNotify(KBookmarkContextMenu* self, const QMetaMethod* signal);
void KBookmarkContextMenu_DisconnectNotify(KBookmarkContextMenu* self, const QMetaMethod* signal);
void KBookmarkContextMenu_OnDisconnectNotify(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseDisconnectNotify(KBookmarkContextMenu* self, const QMetaMethod* signal);
void KBookmarkContextMenu_AddBookmark(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnAddBookmark(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseAddBookmark(KBookmarkContextMenu* self);
void KBookmarkContextMenu_AddFolderActions(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnAddFolderActions(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseAddFolderActions(KBookmarkContextMenu* self);
void KBookmarkContextMenu_AddProperties(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnAddProperties(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseAddProperties(KBookmarkContextMenu* self);
void KBookmarkContextMenu_AddBookmarkActions(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnAddBookmarkActions(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseAddBookmarkActions(KBookmarkContextMenu* self);
void KBookmarkContextMenu_AddOpenFolderInTabs(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnAddOpenFolderInTabs(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseAddOpenFolderInTabs(KBookmarkContextMenu* self);
KBookmarkManager* KBookmarkContextMenu_Manager(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnManager(const KBookmarkContextMenu* self, intptr_t slot);
KBookmarkManager* KBookmarkContextMenu_QBaseManager(const KBookmarkContextMenu* self);
KBookmarkOwner* KBookmarkContextMenu_Owner(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnOwner(const KBookmarkContextMenu* self, intptr_t slot);
KBookmarkOwner* KBookmarkContextMenu_QBaseOwner(const KBookmarkContextMenu* self);
KBookmark* KBookmarkContextMenu_Bookmark(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnBookmark(const KBookmarkContextMenu* self, intptr_t slot);
KBookmark* KBookmarkContextMenu_QBaseBookmark(const KBookmarkContextMenu* self);
int KBookmarkContextMenu_ColumnCount(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnColumnCount(const KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseColumnCount(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_UpdateMicroFocus(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnUpdateMicroFocus(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseUpdateMicroFocus(KBookmarkContextMenu* self);
void KBookmarkContextMenu_Create(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnCreate(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseCreate(KBookmarkContextMenu* self);
void KBookmarkContextMenu_Destroy(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnDestroy(KBookmarkContextMenu* self, intptr_t slot);
void KBookmarkContextMenu_QBaseDestroy(KBookmarkContextMenu* self);
bool KBookmarkContextMenu_FocusNextChild(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnFocusNextChild(KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseFocusNextChild(KBookmarkContextMenu* self);
bool KBookmarkContextMenu_FocusPreviousChild(KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnFocusPreviousChild(KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseFocusPreviousChild(KBookmarkContextMenu* self);
QObject* KBookmarkContextMenu_Sender(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnSender(const KBookmarkContextMenu* self, intptr_t slot);
QObject* KBookmarkContextMenu_QBaseSender(const KBookmarkContextMenu* self);
int KBookmarkContextMenu_SenderSignalIndex(const KBookmarkContextMenu* self);
void KBookmarkContextMenu_OnSenderSignalIndex(const KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseSenderSignalIndex(const KBookmarkContextMenu* self);
int KBookmarkContextMenu_Receivers(const KBookmarkContextMenu* self, const char* signal);
void KBookmarkContextMenu_OnReceivers(const KBookmarkContextMenu* self, intptr_t slot);
int KBookmarkContextMenu_QBaseReceivers(const KBookmarkContextMenu* self, const char* signal);
bool KBookmarkContextMenu_IsSignalConnected(const KBookmarkContextMenu* self, const QMetaMethod* signal);
void KBookmarkContextMenu_OnIsSignalConnected(const KBookmarkContextMenu* self, intptr_t slot);
bool KBookmarkContextMenu_QBaseIsSignalConnected(const KBookmarkContextMenu* self, const QMetaMethod* signal);
double KBookmarkContextMenu_GetDecodedMetricF(const KBookmarkContextMenu* self, int metricA, int metricB);
void KBookmarkContextMenu_OnGetDecodedMetricF(const KBookmarkContextMenu* self, intptr_t slot);
double KBookmarkContextMenu_QBaseGetDecodedMetricF(const KBookmarkContextMenu* self, int metricA, int metricB);
void KBookmarkContextMenu_Delete(KBookmarkContextMenu* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
