#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKPIXMAPREGIONSELECTORDIALOG_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKPIXMAPREGIONSELECTORDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KPixmapRegionSelectorDialog KPixmapRegionSelectorDialog;
typedef struct KPixmapRegionSelectorWidget KPixmapRegionSelectorWidget;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KPixmapRegionSelectorDialog* KPixmapRegionSelectorDialog_new(QWidget* parent);
KPixmapRegionSelectorDialog* KPixmapRegionSelectorDialog_new2();
QMetaObject* KPixmapRegionSelectorDialog_MetaObject(const KPixmapRegionSelectorDialog* self);
void* KPixmapRegionSelectorDialog_Metacast(KPixmapRegionSelectorDialog* self, const char* param1);
int KPixmapRegionSelectorDialog_Metacall(KPixmapRegionSelectorDialog* self, int param1, int param2, void** param3);
libqt_string KPixmapRegionSelectorDialog_Tr(const char* s);
KPixmapRegionSelectorWidget* KPixmapRegionSelectorDialog_PixmapRegionSelectorWidget(const KPixmapRegionSelectorDialog* self);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion(const QPixmap* pixmap);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion2(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage(const QPixmap* pixmap);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage2(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight);
void KPixmapRegionSelectorDialog_AdjustRegionSelectorWidgetSizeToFitScreen(KPixmapRegionSelectorDialog* self);
libqt_string KPixmapRegionSelectorDialog_Tr2(const char* s, const char* c);
libqt_string KPixmapRegionSelectorDialog_Tr3(const char* s, const char* c, int n);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion22(const QPixmap* pixmap, QWidget* parent);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion4(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight, QWidget* parent);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage22(const QPixmap* pixmap, QWidget* parent);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage4(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight, QWidget* parent);
void KPixmapRegionSelectorDialog_OnMetacall(KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseMetacall(KPixmapRegionSelectorDialog* self, int param1, int param2, void** param3);
void KPixmapRegionSelectorDialog_SetVisible(KPixmapRegionSelectorDialog* self, bool visible);
void KPixmapRegionSelectorDialog_OnSetVisible(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseSetVisible(KPixmapRegionSelectorDialog* self, bool visible);
QSize* KPixmapRegionSelectorDialog_SizeHint(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSizeHint(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QSize* KPixmapRegionSelectorDialog_QBaseSizeHint(const KPixmapRegionSelectorDialog* self);
QSize* KPixmapRegionSelectorDialog_MinimumSizeHint(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnMinimumSizeHint(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QSize* KPixmapRegionSelectorDialog_QBaseMinimumSizeHint(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Open(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnOpen(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseOpen(KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_Exec(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnExec(KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseExec(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Done(KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnDone(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDone(KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_Accept(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnAccept(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseAccept(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Reject(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnReject(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseReject(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_KeyPressEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* param1);
void KPixmapRegionSelectorDialog_OnKeyPressEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseKeyPressEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* param1);
void KPixmapRegionSelectorDialog_CloseEvent(KPixmapRegionSelectorDialog* self, QCloseEvent* param1);
void KPixmapRegionSelectorDialog_OnCloseEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseCloseEvent(KPixmapRegionSelectorDialog* self, QCloseEvent* param1);
void KPixmapRegionSelectorDialog_ShowEvent(KPixmapRegionSelectorDialog* self, QShowEvent* param1);
void KPixmapRegionSelectorDialog_OnShowEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseShowEvent(KPixmapRegionSelectorDialog* self, QShowEvent* param1);
void KPixmapRegionSelectorDialog_ResizeEvent(KPixmapRegionSelectorDialog* self, QResizeEvent* param1);
void KPixmapRegionSelectorDialog_OnResizeEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseResizeEvent(KPixmapRegionSelectorDialog* self, QResizeEvent* param1);
void KPixmapRegionSelectorDialog_ContextMenuEvent(KPixmapRegionSelectorDialog* self, QContextMenuEvent* param1);
void KPixmapRegionSelectorDialog_OnContextMenuEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseContextMenuEvent(KPixmapRegionSelectorDialog* self, QContextMenuEvent* param1);
bool KPixmapRegionSelectorDialog_EventFilter(KPixmapRegionSelectorDialog* self, QObject* param1, QEvent* param2);
void KPixmapRegionSelectorDialog_OnEventFilter(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseEventFilter(KPixmapRegionSelectorDialog* self, QObject* param1, QEvent* param2);
int KPixmapRegionSelectorDialog_DevType(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnDevType(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseDevType(const KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_HeightForWidth(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnHeightForWidth(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseHeightForWidth(const KPixmapRegionSelectorDialog* self, int param1);
bool KPixmapRegionSelectorDialog_HasHeightForWidth(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnHasHeightForWidth(const KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseHasHeightForWidth(const KPixmapRegionSelectorDialog* self);
QPaintEngine* KPixmapRegionSelectorDialog_PaintEngine(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnPaintEngine(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QPaintEngine* KPixmapRegionSelectorDialog_QBasePaintEngine(const KPixmapRegionSelectorDialog* self);
bool KPixmapRegionSelectorDialog_Event(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_OnEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_MousePressEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMousePressEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseMousePressEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_MouseReleaseEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMouseReleaseEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseMouseReleaseEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_MouseDoubleClickEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMouseDoubleClickEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseMouseDoubleClickEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_MouseMoveEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMouseMoveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseMouseMoveEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_WheelEvent(KPixmapRegionSelectorDialog* self, QWheelEvent* event);
void KPixmapRegionSelectorDialog_OnWheelEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseWheelEvent(KPixmapRegionSelectorDialog* self, QWheelEvent* event);
void KPixmapRegionSelectorDialog_KeyReleaseEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* event);
void KPixmapRegionSelectorDialog_OnKeyReleaseEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseKeyReleaseEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* event);
void KPixmapRegionSelectorDialog_FocusInEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_OnFocusInEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseFocusInEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_FocusOutEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_OnFocusOutEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseFocusOutEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_EnterEvent(KPixmapRegionSelectorDialog* self, QEnterEvent* event);
void KPixmapRegionSelectorDialog_OnEnterEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseEnterEvent(KPixmapRegionSelectorDialog* self, QEnterEvent* event);
void KPixmapRegionSelectorDialog_LeaveEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_OnLeaveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseLeaveEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_PaintEvent(KPixmapRegionSelectorDialog* self, QPaintEvent* event);
void KPixmapRegionSelectorDialog_OnPaintEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBasePaintEvent(KPixmapRegionSelectorDialog* self, QPaintEvent* event);
void KPixmapRegionSelectorDialog_MoveEvent(KPixmapRegionSelectorDialog* self, QMoveEvent* event);
void KPixmapRegionSelectorDialog_OnMoveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseMoveEvent(KPixmapRegionSelectorDialog* self, QMoveEvent* event);
void KPixmapRegionSelectorDialog_TabletEvent(KPixmapRegionSelectorDialog* self, QTabletEvent* event);
void KPixmapRegionSelectorDialog_OnTabletEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseTabletEvent(KPixmapRegionSelectorDialog* self, QTabletEvent* event);
void KPixmapRegionSelectorDialog_ActionEvent(KPixmapRegionSelectorDialog* self, QActionEvent* event);
void KPixmapRegionSelectorDialog_OnActionEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseActionEvent(KPixmapRegionSelectorDialog* self, QActionEvent* event);
void KPixmapRegionSelectorDialog_DragEnterEvent(KPixmapRegionSelectorDialog* self, QDragEnterEvent* event);
void KPixmapRegionSelectorDialog_OnDragEnterEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDragEnterEvent(KPixmapRegionSelectorDialog* self, QDragEnterEvent* event);
void KPixmapRegionSelectorDialog_DragMoveEvent(KPixmapRegionSelectorDialog* self, QDragMoveEvent* event);
void KPixmapRegionSelectorDialog_OnDragMoveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDragMoveEvent(KPixmapRegionSelectorDialog* self, QDragMoveEvent* event);
void KPixmapRegionSelectorDialog_DragLeaveEvent(KPixmapRegionSelectorDialog* self, QDragLeaveEvent* event);
void KPixmapRegionSelectorDialog_OnDragLeaveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDragLeaveEvent(KPixmapRegionSelectorDialog* self, QDragLeaveEvent* event);
void KPixmapRegionSelectorDialog_DropEvent(KPixmapRegionSelectorDialog* self, QDropEvent* event);
void KPixmapRegionSelectorDialog_OnDropEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDropEvent(KPixmapRegionSelectorDialog* self, QDropEvent* event);
void KPixmapRegionSelectorDialog_HideEvent(KPixmapRegionSelectorDialog* self, QHideEvent* event);
void KPixmapRegionSelectorDialog_OnHideEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseHideEvent(KPixmapRegionSelectorDialog* self, QHideEvent* event);
bool KPixmapRegionSelectorDialog_NativeEvent(KPixmapRegionSelectorDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KPixmapRegionSelectorDialog_OnNativeEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseNativeEvent(KPixmapRegionSelectorDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KPixmapRegionSelectorDialog_ChangeEvent(KPixmapRegionSelectorDialog* self, QEvent* param1);
void KPixmapRegionSelectorDialog_OnChangeEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseChangeEvent(KPixmapRegionSelectorDialog* self, QEvent* param1);
int KPixmapRegionSelectorDialog_Metric(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnMetric(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseMetric(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_InitPainter(const KPixmapRegionSelectorDialog* self, QPainter* painter);
void KPixmapRegionSelectorDialog_OnInitPainter(const KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseInitPainter(const KPixmapRegionSelectorDialog* self, QPainter* painter);
QPaintDevice* KPixmapRegionSelectorDialog_Redirected(const KPixmapRegionSelectorDialog* self, QPoint* offset);
void KPixmapRegionSelectorDialog_OnRedirected(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QPaintDevice* KPixmapRegionSelectorDialog_QBaseRedirected(const KPixmapRegionSelectorDialog* self, QPoint* offset);
QPainter* KPixmapRegionSelectorDialog_SharedPainter(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSharedPainter(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QPainter* KPixmapRegionSelectorDialog_QBaseSharedPainter(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_InputMethodEvent(KPixmapRegionSelectorDialog* self, QInputMethodEvent* param1);
void KPixmapRegionSelectorDialog_OnInputMethodEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseInputMethodEvent(KPixmapRegionSelectorDialog* self, QInputMethodEvent* param1);
QVariant* KPixmapRegionSelectorDialog_InputMethodQuery(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnInputMethodQuery(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QVariant* KPixmapRegionSelectorDialog_QBaseInputMethodQuery(const KPixmapRegionSelectorDialog* self, int param1);
bool KPixmapRegionSelectorDialog_FocusNextPrevChild(KPixmapRegionSelectorDialog* self, bool next);
void KPixmapRegionSelectorDialog_OnFocusNextPrevChild(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseFocusNextPrevChild(KPixmapRegionSelectorDialog* self, bool next);
void KPixmapRegionSelectorDialog_TimerEvent(KPixmapRegionSelectorDialog* self, QTimerEvent* event);
void KPixmapRegionSelectorDialog_OnTimerEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseTimerEvent(KPixmapRegionSelectorDialog* self, QTimerEvent* event);
void KPixmapRegionSelectorDialog_ChildEvent(KPixmapRegionSelectorDialog* self, QChildEvent* event);
void KPixmapRegionSelectorDialog_OnChildEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseChildEvent(KPixmapRegionSelectorDialog* self, QChildEvent* event);
void KPixmapRegionSelectorDialog_CustomEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_OnCustomEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseCustomEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_ConnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_OnConnectNotify(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseConnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_DisconnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_OnDisconnectNotify(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDisconnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_AdjustPosition(KPixmapRegionSelectorDialog* self, QWidget* param1);
void KPixmapRegionSelectorDialog_OnAdjustPosition(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseAdjustPosition(KPixmapRegionSelectorDialog* self, QWidget* param1);
void KPixmapRegionSelectorDialog_UpdateMicroFocus(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnUpdateMicroFocus(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseUpdateMicroFocus(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Create(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnCreate(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseCreate(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Destroy(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnDestroy(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_QBaseDestroy(KPixmapRegionSelectorDialog* self);
bool KPixmapRegionSelectorDialog_FocusNextChild(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnFocusNextChild(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseFocusNextChild(KPixmapRegionSelectorDialog* self);
bool KPixmapRegionSelectorDialog_FocusPreviousChild(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnFocusPreviousChild(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseFocusPreviousChild(KPixmapRegionSelectorDialog* self);
QObject* KPixmapRegionSelectorDialog_Sender(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSender(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QObject* KPixmapRegionSelectorDialog_QBaseSender(const KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_SenderSignalIndex(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSenderSignalIndex(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseSenderSignalIndex(const KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_Receivers(const KPixmapRegionSelectorDialog* self, const char* signal);
void KPixmapRegionSelectorDialog_OnReceivers(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_QBaseReceivers(const KPixmapRegionSelectorDialog* self, const char* signal);
bool KPixmapRegionSelectorDialog_IsSignalConnected(const KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_OnIsSignalConnected(const KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_QBaseIsSignalConnected(const KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
double KPixmapRegionSelectorDialog_GetDecodedMetricF(const KPixmapRegionSelectorDialog* self, int metricA, int metricB);
void KPixmapRegionSelectorDialog_OnGetDecodedMetricF(const KPixmapRegionSelectorDialog* self, intptr_t slot);
double KPixmapRegionSelectorDialog_QBaseGetDecodedMetricF(const KPixmapRegionSelectorDialog* self, int metricA, int metricB);
void KPixmapRegionSelectorDialog_Delete(KPixmapRegionSelectorDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
