#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKTIMECOMBOBOX_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKTIMECOMBOBOX_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KTimeComboBox KTimeComboBox;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTime QTime;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KTimeComboBox* KTimeComboBox_new(QWidget* parent);
KTimeComboBox* KTimeComboBox_new2();
QMetaObject* KTimeComboBox_MetaObject(const KTimeComboBox* self);
void* KTimeComboBox_Metacast(KTimeComboBox* self, const char* param1);
int KTimeComboBox_Metacall(KTimeComboBox* self, int param1, int param2, void** param3);
void KTimeComboBox_OnMetacall(KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_QBaseMetacall(KTimeComboBox* self, int param1, int param2, void** param3);
libqt_string KTimeComboBox_Tr(const char* s);
QTime* KTimeComboBox_Time(const KTimeComboBox* self);
bool KTimeComboBox_IsValid(const KTimeComboBox* self);
bool KTimeComboBox_IsNull(const KTimeComboBox* self);
int KTimeComboBox_Options(const KTimeComboBox* self);
int KTimeComboBox_DisplayFormat(const KTimeComboBox* self);
QTime* KTimeComboBox_MinimumTime(const KTimeComboBox* self);
void KTimeComboBox_ResetMinimumTime(KTimeComboBox* self);
QTime* KTimeComboBox_MaximumTime(const KTimeComboBox* self);
void KTimeComboBox_ResetMaximumTime(KTimeComboBox* self);
void KTimeComboBox_SetTimeRange(KTimeComboBox* self, const QTime* minTime, const QTime* maxTime);
void KTimeComboBox_ResetTimeRange(KTimeComboBox* self);
int KTimeComboBox_TimeListInterval(const KTimeComboBox* self);
libqt_list /* of QTime* */ KTimeComboBox_TimeList(const KTimeComboBox* self);
void KTimeComboBox_TimeEntered(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_Connect_TimeEntered(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_TimeChanged(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_Connect_TimeChanged(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_TimeEdited(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_Connect_TimeEdited(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SetTime(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_SetOptions(KTimeComboBox* self, int options);
void KTimeComboBox_SetDisplayFormat(KTimeComboBox* self, int format);
void KTimeComboBox_SetMinimumTime(KTimeComboBox* self, const QTime* minTime);
void KTimeComboBox_SetMaximumTime(KTimeComboBox* self, const QTime* maxTime);
void KTimeComboBox_SetTimeListInterval(KTimeComboBox* self, int minutes);
void KTimeComboBox_SetTimeList(KTimeComboBox* self, libqt_list /* of QTime* */ timeList);
bool KTimeComboBox_EventFilter(KTimeComboBox* self, QObject* object, QEvent* event);
void KTimeComboBox_OnEventFilter(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseEventFilter(KTimeComboBox* self, QObject* object, QEvent* event);
void KTimeComboBox_ShowPopup(KTimeComboBox* self);
void KTimeComboBox_OnShowPopup(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseShowPopup(KTimeComboBox* self);
void KTimeComboBox_HidePopup(KTimeComboBox* self);
void KTimeComboBox_OnHidePopup(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseHidePopup(KTimeComboBox* self);
void KTimeComboBox_MousePressEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_OnMousePressEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseMousePressEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_WheelEvent(KTimeComboBox* self, QWheelEvent* event);
void KTimeComboBox_OnWheelEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseWheelEvent(KTimeComboBox* self, QWheelEvent* event);
void KTimeComboBox_KeyPressEvent(KTimeComboBox* self, QKeyEvent* event);
void KTimeComboBox_OnKeyPressEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseKeyPressEvent(KTimeComboBox* self, QKeyEvent* event);
void KTimeComboBox_FocusInEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_OnFocusInEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseFocusInEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_FocusOutEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_OnFocusOutEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseFocusOutEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_ResizeEvent(KTimeComboBox* self, QResizeEvent* event);
void KTimeComboBox_OnResizeEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseResizeEvent(KTimeComboBox* self, QResizeEvent* event);
void KTimeComboBox_AssignTime(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_OnAssignTime(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseAssignTime(KTimeComboBox* self, const QTime* time);
libqt_string KTimeComboBox_Tr2(const char* s, const char* c);
libqt_string KTimeComboBox_Tr3(const char* s, const char* c, int n);
void KTimeComboBox_SetTimeRange3(KTimeComboBox* self, const QTime* minTime, const QTime* maxTime, const libqt_string minWarnMsg);
void KTimeComboBox_SetTimeRange4(KTimeComboBox* self, const QTime* minTime, const QTime* maxTime, const libqt_string minWarnMsg, const libqt_string maxWarnMsg);
void KTimeComboBox_SetMinimumTime2(KTimeComboBox* self, const QTime* minTime, const libqt_string minWarnMsg);
void KTimeComboBox_SetMaximumTime2(KTimeComboBox* self, const QTime* maxTime, const libqt_string maxWarnMsg);
void KTimeComboBox_SetTimeList2(KTimeComboBox* self, libqt_list /* of QTime* */ timeList, const libqt_string minWarnMsg);
void KTimeComboBox_SetTimeList3(KTimeComboBox* self, libqt_list /* of QTime* */ timeList, const libqt_string minWarnMsg, const libqt_string maxWarnMsg);
void KTimeComboBox_SetModel(KTimeComboBox* self, QAbstractItemModel* model);
void KTimeComboBox_OnSetModel(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseSetModel(KTimeComboBox* self, QAbstractItemModel* model);
QSize* KTimeComboBox_SizeHint(const KTimeComboBox* self);
void KTimeComboBox_OnSizeHint(const KTimeComboBox* self, intptr_t slot);
QSize* KTimeComboBox_QBaseSizeHint(const KTimeComboBox* self);
QSize* KTimeComboBox_MinimumSizeHint(const KTimeComboBox* self);
void KTimeComboBox_OnMinimumSizeHint(const KTimeComboBox* self, intptr_t slot);
QSize* KTimeComboBox_QBaseMinimumSizeHint(const KTimeComboBox* self);
bool KTimeComboBox_Event(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_OnEvent(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseEvent(KTimeComboBox* self, QEvent* event);
QVariant* KTimeComboBox_InputMethodQuery(const KTimeComboBox* self, int param1);
void KTimeComboBox_OnInputMethodQuery(const KTimeComboBox* self, intptr_t slot);
QVariant* KTimeComboBox_QBaseInputMethodQuery(const KTimeComboBox* self, int param1);
void KTimeComboBox_ChangeEvent(KTimeComboBox* self, QEvent* e);
void KTimeComboBox_OnChangeEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseChangeEvent(KTimeComboBox* self, QEvent* e);
void KTimeComboBox_PaintEvent(KTimeComboBox* self, QPaintEvent* e);
void KTimeComboBox_OnPaintEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBasePaintEvent(KTimeComboBox* self, QPaintEvent* e);
void KTimeComboBox_ShowEvent(KTimeComboBox* self, QShowEvent* e);
void KTimeComboBox_OnShowEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseShowEvent(KTimeComboBox* self, QShowEvent* e);
void KTimeComboBox_HideEvent(KTimeComboBox* self, QHideEvent* e);
void KTimeComboBox_OnHideEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseHideEvent(KTimeComboBox* self, QHideEvent* e);
void KTimeComboBox_MouseReleaseEvent(KTimeComboBox* self, QMouseEvent* e);
void KTimeComboBox_OnMouseReleaseEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseMouseReleaseEvent(KTimeComboBox* self, QMouseEvent* e);
void KTimeComboBox_KeyReleaseEvent(KTimeComboBox* self, QKeyEvent* e);
void KTimeComboBox_OnKeyReleaseEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseKeyReleaseEvent(KTimeComboBox* self, QKeyEvent* e);
void KTimeComboBox_ContextMenuEvent(KTimeComboBox* self, QContextMenuEvent* e);
void KTimeComboBox_OnContextMenuEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseContextMenuEvent(KTimeComboBox* self, QContextMenuEvent* e);
void KTimeComboBox_InputMethodEvent(KTimeComboBox* self, QInputMethodEvent* param1);
void KTimeComboBox_OnInputMethodEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseInputMethodEvent(KTimeComboBox* self, QInputMethodEvent* param1);
void KTimeComboBox_InitStyleOption(const KTimeComboBox* self, QStyleOptionComboBox* option);
void KTimeComboBox_OnInitStyleOption(const KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseInitStyleOption(const KTimeComboBox* self, QStyleOptionComboBox* option);
int KTimeComboBox_DevType(const KTimeComboBox* self);
void KTimeComboBox_OnDevType(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_QBaseDevType(const KTimeComboBox* self);
void KTimeComboBox_SetVisible(KTimeComboBox* self, bool visible);
void KTimeComboBox_OnSetVisible(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseSetVisible(KTimeComboBox* self, bool visible);
int KTimeComboBox_HeightForWidth(const KTimeComboBox* self, int param1);
void KTimeComboBox_OnHeightForWidth(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_QBaseHeightForWidth(const KTimeComboBox* self, int param1);
bool KTimeComboBox_HasHeightForWidth(const KTimeComboBox* self);
void KTimeComboBox_OnHasHeightForWidth(const KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseHasHeightForWidth(const KTimeComboBox* self);
QPaintEngine* KTimeComboBox_PaintEngine(const KTimeComboBox* self);
void KTimeComboBox_OnPaintEngine(const KTimeComboBox* self, intptr_t slot);
QPaintEngine* KTimeComboBox_QBasePaintEngine(const KTimeComboBox* self);
void KTimeComboBox_MouseDoubleClickEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_OnMouseDoubleClickEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseMouseDoubleClickEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_MouseMoveEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_OnMouseMoveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseMouseMoveEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_EnterEvent(KTimeComboBox* self, QEnterEvent* event);
void KTimeComboBox_OnEnterEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseEnterEvent(KTimeComboBox* self, QEnterEvent* event);
void KTimeComboBox_LeaveEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_OnLeaveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseLeaveEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_MoveEvent(KTimeComboBox* self, QMoveEvent* event);
void KTimeComboBox_OnMoveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseMoveEvent(KTimeComboBox* self, QMoveEvent* event);
void KTimeComboBox_CloseEvent(KTimeComboBox* self, QCloseEvent* event);
void KTimeComboBox_OnCloseEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseCloseEvent(KTimeComboBox* self, QCloseEvent* event);
void KTimeComboBox_TabletEvent(KTimeComboBox* self, QTabletEvent* event);
void KTimeComboBox_OnTabletEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseTabletEvent(KTimeComboBox* self, QTabletEvent* event);
void KTimeComboBox_ActionEvent(KTimeComboBox* self, QActionEvent* event);
void KTimeComboBox_OnActionEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseActionEvent(KTimeComboBox* self, QActionEvent* event);
void KTimeComboBox_DragEnterEvent(KTimeComboBox* self, QDragEnterEvent* event);
void KTimeComboBox_OnDragEnterEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseDragEnterEvent(KTimeComboBox* self, QDragEnterEvent* event);
void KTimeComboBox_DragMoveEvent(KTimeComboBox* self, QDragMoveEvent* event);
void KTimeComboBox_OnDragMoveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseDragMoveEvent(KTimeComboBox* self, QDragMoveEvent* event);
void KTimeComboBox_DragLeaveEvent(KTimeComboBox* self, QDragLeaveEvent* event);
void KTimeComboBox_OnDragLeaveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseDragLeaveEvent(KTimeComboBox* self, QDragLeaveEvent* event);
void KTimeComboBox_DropEvent(KTimeComboBox* self, QDropEvent* event);
void KTimeComboBox_OnDropEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseDropEvent(KTimeComboBox* self, QDropEvent* event);
bool KTimeComboBox_NativeEvent(KTimeComboBox* self, const libqt_string eventType, void* message, intptr_t* result);
void KTimeComboBox_OnNativeEvent(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseNativeEvent(KTimeComboBox* self, const libqt_string eventType, void* message, intptr_t* result);
int KTimeComboBox_Metric(const KTimeComboBox* self, int param1);
void KTimeComboBox_OnMetric(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_QBaseMetric(const KTimeComboBox* self, int param1);
void KTimeComboBox_InitPainter(const KTimeComboBox* self, QPainter* painter);
void KTimeComboBox_OnInitPainter(const KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseInitPainter(const KTimeComboBox* self, QPainter* painter);
QPaintDevice* KTimeComboBox_Redirected(const KTimeComboBox* self, QPoint* offset);
void KTimeComboBox_OnRedirected(const KTimeComboBox* self, intptr_t slot);
QPaintDevice* KTimeComboBox_QBaseRedirected(const KTimeComboBox* self, QPoint* offset);
QPainter* KTimeComboBox_SharedPainter(const KTimeComboBox* self);
void KTimeComboBox_OnSharedPainter(const KTimeComboBox* self, intptr_t slot);
QPainter* KTimeComboBox_QBaseSharedPainter(const KTimeComboBox* self);
bool KTimeComboBox_FocusNextPrevChild(KTimeComboBox* self, bool next);
void KTimeComboBox_OnFocusNextPrevChild(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseFocusNextPrevChild(KTimeComboBox* self, bool next);
void KTimeComboBox_TimerEvent(KTimeComboBox* self, QTimerEvent* event);
void KTimeComboBox_OnTimerEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseTimerEvent(KTimeComboBox* self, QTimerEvent* event);
void KTimeComboBox_ChildEvent(KTimeComboBox* self, QChildEvent* event);
void KTimeComboBox_OnChildEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseChildEvent(KTimeComboBox* self, QChildEvent* event);
void KTimeComboBox_CustomEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_OnCustomEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseCustomEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_ConnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_OnConnectNotify(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseConnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_DisconnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_OnDisconnectNotify(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseDisconnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_UpdateMicroFocus(KTimeComboBox* self);
void KTimeComboBox_OnUpdateMicroFocus(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseUpdateMicroFocus(KTimeComboBox* self);
void KTimeComboBox_Create(KTimeComboBox* self);
void KTimeComboBox_OnCreate(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseCreate(KTimeComboBox* self);
void KTimeComboBox_Destroy(KTimeComboBox* self);
void KTimeComboBox_OnDestroy(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_QBaseDestroy(KTimeComboBox* self);
bool KTimeComboBox_FocusNextChild(KTimeComboBox* self);
void KTimeComboBox_OnFocusNextChild(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseFocusNextChild(KTimeComboBox* self);
bool KTimeComboBox_FocusPreviousChild(KTimeComboBox* self);
void KTimeComboBox_OnFocusPreviousChild(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseFocusPreviousChild(KTimeComboBox* self);
QObject* KTimeComboBox_Sender(const KTimeComboBox* self);
void KTimeComboBox_OnSender(const KTimeComboBox* self, intptr_t slot);
QObject* KTimeComboBox_QBaseSender(const KTimeComboBox* self);
int KTimeComboBox_SenderSignalIndex(const KTimeComboBox* self);
void KTimeComboBox_OnSenderSignalIndex(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_QBaseSenderSignalIndex(const KTimeComboBox* self);
int KTimeComboBox_Receivers(const KTimeComboBox* self, const char* signal);
void KTimeComboBox_OnReceivers(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_QBaseReceivers(const KTimeComboBox* self, const char* signal);
bool KTimeComboBox_IsSignalConnected(const KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_OnIsSignalConnected(const KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_QBaseIsSignalConnected(const KTimeComboBox* self, const QMetaMethod* signal);
double KTimeComboBox_GetDecodedMetricF(const KTimeComboBox* self, int metricA, int metricB);
void KTimeComboBox_OnGetDecodedMetricF(const KTimeComboBox* self, intptr_t slot);
double KTimeComboBox_QBaseGetDecodedMetricF(const KTimeComboBox* self, int metricA, int metricB);
void KTimeComboBox_Delete(KTimeComboBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
