#pragma once
#ifndef SRC_EXTRAS_KIOC_LIBKDIRSORTFILTERPROXYMODEL_H
#define SRC_EXTRAS_KIOC_LIBKDIRSORTFILTERPROXYMODEL_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KCategorizedSortFilterProxyModel KCategorizedSortFilterProxyModel;
typedef struct KDirSortFilterProxyModel KDirSortFilterProxyModel;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractProxyModel QAbstractProxyModel;
typedef struct QChildEvent QChildEvent;
typedef struct QDataStream QDataStream;
typedef struct QEvent QEvent;
typedef struct QFileInfo QFileInfo;
typedef struct QItemSelection QItemSelection;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QModelRoleDataSpan QModelRoleDataSpan;
typedef struct QObject QObject;
typedef struct QSize QSize;
typedef struct QSortFilterProxyModel QSortFilterProxyModel;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
#endif

KDirSortFilterProxyModel* KDirSortFilterProxyModel_new();
KDirSortFilterProxyModel* KDirSortFilterProxyModel_new2(QObject* parent);
QMetaObject* KDirSortFilterProxyModel_MetaObject(const KDirSortFilterProxyModel* self);
void* KDirSortFilterProxyModel_Metacast(KDirSortFilterProxyModel* self, const char* param1);
int KDirSortFilterProxyModel_Metacall(KDirSortFilterProxyModel* self, int param1, int param2, void** param3);
libqt_string KDirSortFilterProxyModel_Tr(const char* s);
bool KDirSortFilterProxyModel_HasChildren(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
bool KDirSortFilterProxyModel_CanFetchMore(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
int KDirSortFilterProxyModel_PointsForPermissions(const QFileInfo* info);
void KDirSortFilterProxyModel_SetSortFoldersFirst(KDirSortFilterProxyModel* self, bool foldersFirst);
bool KDirSortFilterProxyModel_SortFoldersFirst(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_SetSortHiddenFilesLast(KDirSortFilterProxyModel* self, bool hiddenFilesLast);
bool KDirSortFilterProxyModel_SortHiddenFilesLast(const KDirSortFilterProxyModel* self);
int KDirSortFilterProxyModel_SupportedDragOptions(const KDirSortFilterProxyModel* self);
bool KDirSortFilterProxyModel_SubSortLessThan(const KDirSortFilterProxyModel* self, const QModelIndex* left, const QModelIndex* right);
libqt_string KDirSortFilterProxyModel_Tr2(const char* s, const char* c);
libqt_string KDirSortFilterProxyModel_Tr3(const char* s, const char* c, int n);
void KDirSortFilterProxyModel_OnMetacall(KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseMetacall(KDirSortFilterProxyModel* self, int param1, int param2, void** param3);
void KDirSortFilterProxyModel_OnHasChildren(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseHasChildren(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnCanFetchMore(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseCanFetchMore(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnSubSortLessThan(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseSubSortLessThan(const KDirSortFilterProxyModel* self, const QModelIndex* left, const QModelIndex* right);
void KDirSortFilterProxyModel_Sort(KDirSortFilterProxyModel* self, int column, int order);
void KDirSortFilterProxyModel_OnSort(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseSort(KDirSortFilterProxyModel* self, int column, int order);
bool KDirSortFilterProxyModel_LessThan(const KDirSortFilterProxyModel* self, const QModelIndex* left, const QModelIndex* right);
void KDirSortFilterProxyModel_OnLessThan(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseLessThan(const KDirSortFilterProxyModel* self, const QModelIndex* left, const QModelIndex* right);
int KDirSortFilterProxyModel_CompareCategories(const KDirSortFilterProxyModel* self, const QModelIndex* left, const QModelIndex* right);
void KDirSortFilterProxyModel_OnCompareCategories(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseCompareCategories(const KDirSortFilterProxyModel* self, const QModelIndex* left, const QModelIndex* right);
void KDirSortFilterProxyModel_SetSourceModel(KDirSortFilterProxyModel* self, QAbstractItemModel* sourceModel);
void KDirSortFilterProxyModel_OnSetSourceModel(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseSetSourceModel(KDirSortFilterProxyModel* self, QAbstractItemModel* sourceModel);
QModelIndex* KDirSortFilterProxyModel_MapToSource(const KDirSortFilterProxyModel* self, const QModelIndex* proxyIndex);
void KDirSortFilterProxyModel_OnMapToSource(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseMapToSource(const KDirSortFilterProxyModel* self, const QModelIndex* proxyIndex);
QModelIndex* KDirSortFilterProxyModel_MapFromSource(const KDirSortFilterProxyModel* self, const QModelIndex* sourceIndex);
void KDirSortFilterProxyModel_OnMapFromSource(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseMapFromSource(const KDirSortFilterProxyModel* self, const QModelIndex* sourceIndex);
QItemSelection* KDirSortFilterProxyModel_MapSelectionToSource(const KDirSortFilterProxyModel* self, const QItemSelection* proxySelection);
void KDirSortFilterProxyModel_OnMapSelectionToSource(const KDirSortFilterProxyModel* self, intptr_t slot);
QItemSelection* KDirSortFilterProxyModel_QBaseMapSelectionToSource(const KDirSortFilterProxyModel* self, const QItemSelection* proxySelection);
QItemSelection* KDirSortFilterProxyModel_MapSelectionFromSource(const KDirSortFilterProxyModel* self, const QItemSelection* sourceSelection);
void KDirSortFilterProxyModel_OnMapSelectionFromSource(const KDirSortFilterProxyModel* self, intptr_t slot);
QItemSelection* KDirSortFilterProxyModel_QBaseMapSelectionFromSource(const KDirSortFilterProxyModel* self, const QItemSelection* sourceSelection);
bool KDirSortFilterProxyModel_FilterAcceptsRow(const KDirSortFilterProxyModel* self, int source_row, const QModelIndex* source_parent);
void KDirSortFilterProxyModel_OnFilterAcceptsRow(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseFilterAcceptsRow(const KDirSortFilterProxyModel* self, int source_row, const QModelIndex* source_parent);
bool KDirSortFilterProxyModel_FilterAcceptsColumn(const KDirSortFilterProxyModel* self, int source_column, const QModelIndex* source_parent);
void KDirSortFilterProxyModel_OnFilterAcceptsColumn(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseFilterAcceptsColumn(const KDirSortFilterProxyModel* self, int source_column, const QModelIndex* source_parent);
QModelIndex* KDirSortFilterProxyModel_Index(const KDirSortFilterProxyModel* self, int row, int column, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnIndex(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseIndex(const KDirSortFilterProxyModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* KDirSortFilterProxyModel_Parent(const KDirSortFilterProxyModel* self, const QModelIndex* child);
void KDirSortFilterProxyModel_OnParent(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseParent(const KDirSortFilterProxyModel* self, const QModelIndex* child);
QModelIndex* KDirSortFilterProxyModel_Sibling(const KDirSortFilterProxyModel* self, int row, int column, const QModelIndex* idx);
void KDirSortFilterProxyModel_OnSibling(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseSibling(const KDirSortFilterProxyModel* self, int row, int column, const QModelIndex* idx);
int KDirSortFilterProxyModel_RowCount(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnRowCount(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseRowCount(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
int KDirSortFilterProxyModel_ColumnCount(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnColumnCount(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseColumnCount(const KDirSortFilterProxyModel* self, const QModelIndex* parent);
QVariant* KDirSortFilterProxyModel_Data(const KDirSortFilterProxyModel* self, const QModelIndex* index, int role);
void KDirSortFilterProxyModel_OnData(const KDirSortFilterProxyModel* self, intptr_t slot);
QVariant* KDirSortFilterProxyModel_QBaseData(const KDirSortFilterProxyModel* self, const QModelIndex* index, int role);
bool KDirSortFilterProxyModel_SetData(KDirSortFilterProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
void KDirSortFilterProxyModel_OnSetData(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseSetData(KDirSortFilterProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
QVariant* KDirSortFilterProxyModel_HeaderData(const KDirSortFilterProxyModel* self, int section, int orientation, int role);
void KDirSortFilterProxyModel_OnHeaderData(const KDirSortFilterProxyModel* self, intptr_t slot);
QVariant* KDirSortFilterProxyModel_QBaseHeaderData(const KDirSortFilterProxyModel* self, int section, int orientation, int role);
bool KDirSortFilterProxyModel_SetHeaderData(KDirSortFilterProxyModel* self, int section, int orientation, const QVariant* value, int role);
void KDirSortFilterProxyModel_OnSetHeaderData(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseSetHeaderData(KDirSortFilterProxyModel* self, int section, int orientation, const QVariant* value, int role);
QMimeData* KDirSortFilterProxyModel_MimeData(const KDirSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
void KDirSortFilterProxyModel_OnMimeData(const KDirSortFilterProxyModel* self, intptr_t slot);
QMimeData* KDirSortFilterProxyModel_QBaseMimeData(const KDirSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
bool KDirSortFilterProxyModel_DropMimeData(KDirSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnDropMimeData(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseDropMimeData(KDirSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
bool KDirSortFilterProxyModel_InsertRows(KDirSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnInsertRows(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseInsertRows(KDirSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
bool KDirSortFilterProxyModel_InsertColumns(KDirSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnInsertColumns(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseInsertColumns(KDirSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
bool KDirSortFilterProxyModel_RemoveRows(KDirSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnRemoveRows(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseRemoveRows(KDirSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
bool KDirSortFilterProxyModel_RemoveColumns(KDirSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnRemoveColumns(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseRemoveColumns(KDirSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
void KDirSortFilterProxyModel_FetchMore(KDirSortFilterProxyModel* self, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnFetchMore(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseFetchMore(KDirSortFilterProxyModel* self, const QModelIndex* parent);
int KDirSortFilterProxyModel_Flags(const KDirSortFilterProxyModel* self, const QModelIndex* index);
void KDirSortFilterProxyModel_OnFlags(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseFlags(const KDirSortFilterProxyModel* self, const QModelIndex* index);
QModelIndex* KDirSortFilterProxyModel_Buddy(const KDirSortFilterProxyModel* self, const QModelIndex* index);
void KDirSortFilterProxyModel_OnBuddy(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseBuddy(const KDirSortFilterProxyModel* self, const QModelIndex* index);
libqt_list /* of QModelIndex* */ KDirSortFilterProxyModel_Match(const KDirSortFilterProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
void KDirSortFilterProxyModel_OnMatch(const KDirSortFilterProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ KDirSortFilterProxyModel_QBaseMatch(const KDirSortFilterProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
QSize* KDirSortFilterProxyModel_Span(const KDirSortFilterProxyModel* self, const QModelIndex* index);
void KDirSortFilterProxyModel_OnSpan(const KDirSortFilterProxyModel* self, intptr_t slot);
QSize* KDirSortFilterProxyModel_QBaseSpan(const KDirSortFilterProxyModel* self, const QModelIndex* index);
libqt_list /* of libqt_string */ KDirSortFilterProxyModel_MimeTypes(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnMimeTypes(const KDirSortFilterProxyModel* self, intptr_t slot);
libqt_list /* of libqt_string */ KDirSortFilterProxyModel_QBaseMimeTypes(const KDirSortFilterProxyModel* self);
int KDirSortFilterProxyModel_SupportedDropActions(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnSupportedDropActions(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseSupportedDropActions(const KDirSortFilterProxyModel* self);
bool KDirSortFilterProxyModel_Submit(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnSubmit(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseSubmit(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_Revert(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnRevert(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseRevert(KDirSortFilterProxyModel* self);
libqt_map /* of int to QVariant* */ KDirSortFilterProxyModel_ItemData(const KDirSortFilterProxyModel* self, const QModelIndex* index);
void KDirSortFilterProxyModel_OnItemData(const KDirSortFilterProxyModel* self, intptr_t slot);
libqt_map /* of int to QVariant* */ KDirSortFilterProxyModel_QBaseItemData(const KDirSortFilterProxyModel* self, const QModelIndex* index);
bool KDirSortFilterProxyModel_SetItemData(KDirSortFilterProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
void KDirSortFilterProxyModel_OnSetItemData(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseSetItemData(KDirSortFilterProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
bool KDirSortFilterProxyModel_ClearItemData(KDirSortFilterProxyModel* self, const QModelIndex* index);
void KDirSortFilterProxyModel_OnClearItemData(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseClearItemData(KDirSortFilterProxyModel* self, const QModelIndex* index);
bool KDirSortFilterProxyModel_CanDropMimeData(const KDirSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void KDirSortFilterProxyModel_OnCanDropMimeData(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseCanDropMimeData(const KDirSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
int KDirSortFilterProxyModel_SupportedDragActions(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnSupportedDragActions(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseSupportedDragActions(const KDirSortFilterProxyModel* self);
libqt_map /* of int to libqt_string */ KDirSortFilterProxyModel_RoleNames(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnRoleNames(const KDirSortFilterProxyModel* self, intptr_t slot);
libqt_map /* of int to libqt_string */ KDirSortFilterProxyModel_QBaseRoleNames(const KDirSortFilterProxyModel* self);
bool KDirSortFilterProxyModel_MoveRows(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
void KDirSortFilterProxyModel_OnMoveRows(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseMoveRows(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
bool KDirSortFilterProxyModel_MoveColumns(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void KDirSortFilterProxyModel_OnMoveColumns(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseMoveColumns(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void KDirSortFilterProxyModel_MultiData(const KDirSortFilterProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void KDirSortFilterProxyModel_OnMultiData(const KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseMultiData(const KDirSortFilterProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void KDirSortFilterProxyModel_ResetInternalData(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnResetInternalData(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseResetInternalData(KDirSortFilterProxyModel* self);
bool KDirSortFilterProxyModel_Event(KDirSortFilterProxyModel* self, QEvent* event);
void KDirSortFilterProxyModel_OnEvent(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseEvent(KDirSortFilterProxyModel* self, QEvent* event);
bool KDirSortFilterProxyModel_EventFilter(KDirSortFilterProxyModel* self, QObject* watched, QEvent* event);
void KDirSortFilterProxyModel_OnEventFilter(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseEventFilter(KDirSortFilterProxyModel* self, QObject* watched, QEvent* event);
void KDirSortFilterProxyModel_TimerEvent(KDirSortFilterProxyModel* self, QTimerEvent* event);
void KDirSortFilterProxyModel_OnTimerEvent(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseTimerEvent(KDirSortFilterProxyModel* self, QTimerEvent* event);
void KDirSortFilterProxyModel_ChildEvent(KDirSortFilterProxyModel* self, QChildEvent* event);
void KDirSortFilterProxyModel_OnChildEvent(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseChildEvent(KDirSortFilterProxyModel* self, QChildEvent* event);
void KDirSortFilterProxyModel_CustomEvent(KDirSortFilterProxyModel* self, QEvent* event);
void KDirSortFilterProxyModel_OnCustomEvent(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseCustomEvent(KDirSortFilterProxyModel* self, QEvent* event);
void KDirSortFilterProxyModel_ConnectNotify(KDirSortFilterProxyModel* self, const QMetaMethod* signal);
void KDirSortFilterProxyModel_OnConnectNotify(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseConnectNotify(KDirSortFilterProxyModel* self, const QMetaMethod* signal);
void KDirSortFilterProxyModel_DisconnectNotify(KDirSortFilterProxyModel* self, const QMetaMethod* signal);
void KDirSortFilterProxyModel_OnDisconnectNotify(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseDisconnectNotify(KDirSortFilterProxyModel* self, const QMetaMethod* signal);
void KDirSortFilterProxyModel_InvalidateFilter(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnInvalidateFilter(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseInvalidateFilter(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_InvalidateRowsFilter(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnInvalidateRowsFilter(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseInvalidateRowsFilter(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_InvalidateColumnsFilter(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnInvalidateColumnsFilter(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseInvalidateColumnsFilter(KDirSortFilterProxyModel* self);
QModelIndex* KDirSortFilterProxyModel_CreateSourceIndex(const KDirSortFilterProxyModel* self, int row, int col, void* internalPtr);
void KDirSortFilterProxyModel_OnCreateSourceIndex(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseCreateSourceIndex(const KDirSortFilterProxyModel* self, int row, int col, void* internalPtr);
QModelIndex* KDirSortFilterProxyModel_CreateIndex(const KDirSortFilterProxyModel* self, int row, int column);
void KDirSortFilterProxyModel_OnCreateIndex(const KDirSortFilterProxyModel* self, intptr_t slot);
QModelIndex* KDirSortFilterProxyModel_QBaseCreateIndex(const KDirSortFilterProxyModel* self, int row, int column);
void KDirSortFilterProxyModel_EncodeData(const KDirSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
void KDirSortFilterProxyModel_OnEncodeData(const KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEncodeData(const KDirSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
bool KDirSortFilterProxyModel_DecodeData(KDirSortFilterProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void KDirSortFilterProxyModel_OnDecodeData(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseDecodeData(KDirSortFilterProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void KDirSortFilterProxyModel_BeginInsertRows(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_OnBeginInsertRows(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseBeginInsertRows(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_EndInsertRows(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndInsertRows(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndInsertRows(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_BeginRemoveRows(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_OnBeginRemoveRows(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseBeginRemoveRows(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_EndRemoveRows(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndRemoveRows(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndRemoveRows(KDirSortFilterProxyModel* self);
bool KDirSortFilterProxyModel_BeginMoveRows(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void KDirSortFilterProxyModel_OnBeginMoveRows(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseBeginMoveRows(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void KDirSortFilterProxyModel_EndMoveRows(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndMoveRows(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndMoveRows(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_BeginInsertColumns(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_OnBeginInsertColumns(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseBeginInsertColumns(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_EndInsertColumns(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndInsertColumns(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndInsertColumns(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_BeginRemoveColumns(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_OnBeginRemoveColumns(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseBeginRemoveColumns(KDirSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void KDirSortFilterProxyModel_EndRemoveColumns(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndRemoveColumns(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndRemoveColumns(KDirSortFilterProxyModel* self);
bool KDirSortFilterProxyModel_BeginMoveColumns(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void KDirSortFilterProxyModel_OnBeginMoveColumns(KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseBeginMoveColumns(KDirSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void KDirSortFilterProxyModel_EndMoveColumns(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndMoveColumns(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndMoveColumns(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_BeginResetModel(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnBeginResetModel(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseBeginResetModel(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_EndResetModel(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnEndResetModel(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseEndResetModel(KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_ChangePersistentIndex(KDirSortFilterProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void KDirSortFilterProxyModel_OnChangePersistentIndex(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseChangePersistentIndex(KDirSortFilterProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void KDirSortFilterProxyModel_ChangePersistentIndexList(KDirSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
void KDirSortFilterProxyModel_OnChangePersistentIndexList(KDirSortFilterProxyModel* self, intptr_t slot);
void KDirSortFilterProxyModel_QBaseChangePersistentIndexList(KDirSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
libqt_list /* of QModelIndex* */ KDirSortFilterProxyModel_PersistentIndexList(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnPersistentIndexList(const KDirSortFilterProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ KDirSortFilterProxyModel_QBasePersistentIndexList(const KDirSortFilterProxyModel* self);
QObject* KDirSortFilterProxyModel_Sender(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnSender(const KDirSortFilterProxyModel* self, intptr_t slot);
QObject* KDirSortFilterProxyModel_QBaseSender(const KDirSortFilterProxyModel* self);
int KDirSortFilterProxyModel_SenderSignalIndex(const KDirSortFilterProxyModel* self);
void KDirSortFilterProxyModel_OnSenderSignalIndex(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseSenderSignalIndex(const KDirSortFilterProxyModel* self);
int KDirSortFilterProxyModel_Receivers(const KDirSortFilterProxyModel* self, const char* signal);
void KDirSortFilterProxyModel_OnReceivers(const KDirSortFilterProxyModel* self, intptr_t slot);
int KDirSortFilterProxyModel_QBaseReceivers(const KDirSortFilterProxyModel* self, const char* signal);
bool KDirSortFilterProxyModel_IsSignalConnected(const KDirSortFilterProxyModel* self, const QMetaMethod* signal);
void KDirSortFilterProxyModel_OnIsSignalConnected(const KDirSortFilterProxyModel* self, intptr_t slot);
bool KDirSortFilterProxyModel_QBaseIsSignalConnected(const KDirSortFilterProxyModel* self, const QMetaMethod* signal);
void KDirSortFilterProxyModel_Delete(KDirSortFilterProxyModel* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
