#pragma once
#ifndef SRC_EXTRAS_KTEXTWIDGETSC_LIBKFINDDIALOG_H
#define SRC_EXTRAS_KTEXTWIDGETSC_LIBKFINDDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KFindDialog KFindDialog;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KFindDialog* KFindDialog_new(QWidget* parent);
KFindDialog* KFindDialog_new2();
KFindDialog* KFindDialog_new3(QWidget* parent, long options);
KFindDialog* KFindDialog_new4(QWidget* parent, long options, const libqt_list /* of libqt_string */ findStrings);
KFindDialog* KFindDialog_new5(QWidget* parent, long options, const libqt_list /* of libqt_string */ findStrings, bool hasSelection);
KFindDialog* KFindDialog_new6(QWidget* parent, long options, const libqt_list /* of libqt_string */ findStrings, bool hasSelection, bool replaceDialog);
QMetaObject* KFindDialog_MetaObject(const KFindDialog* self);
void* KFindDialog_Metacast(KFindDialog* self, const char* param1);
int KFindDialog_Metacall(KFindDialog* self, int param1, int param2, void** param3);
libqt_string KFindDialog_Tr(const char* s);
void KFindDialog_SetFindHistory(KFindDialog* self, const libqt_list /* of libqt_string */ history);
libqt_list /* of libqt_string */ KFindDialog_FindHistory(const KFindDialog* self);
void KFindDialog_SetHasSelection(KFindDialog* self, bool hasSelection);
void KFindDialog_SetHasCursor(KFindDialog* self, bool hasCursor);
void KFindDialog_SetSupportsBackwardsFind(KFindDialog* self, bool supports);
void KFindDialog_SetSupportsCaseSensitiveFind(KFindDialog* self, bool supports);
void KFindDialog_SetSupportsWholeWordsFind(KFindDialog* self, bool supports);
void KFindDialog_SetSupportsRegularExpressionFind(KFindDialog* self, bool supports);
void KFindDialog_SetOptions(KFindDialog* self, long options);
long KFindDialog_Options(const KFindDialog* self);
libqt_string KFindDialog_Pattern(const KFindDialog* self);
void KFindDialog_SetPattern(KFindDialog* self, const libqt_string pattern);
QWidget* KFindDialog_FindExtension(const KFindDialog* self);
void KFindDialog_OptionsChanged(KFindDialog* self);
void KFindDialog_Connect_OptionsChanged(KFindDialog* self, intptr_t slot);
void KFindDialog_OkClicked(KFindDialog* self);
void KFindDialog_Connect_OkClicked(KFindDialog* self, intptr_t slot);
void KFindDialog_CancelClicked(KFindDialog* self);
void KFindDialog_Connect_CancelClicked(KFindDialog* self, intptr_t slot);
void KFindDialog_ShowEvent(KFindDialog* self, QShowEvent* param1);
libqt_string KFindDialog_Tr2(const char* s, const char* c);
libqt_string KFindDialog_Tr3(const char* s, const char* c, int n);
void KFindDialog_OnMetacall(KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseMetacall(KFindDialog* self, int param1, int param2, void** param3);
void KFindDialog_OnShowEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseShowEvent(KFindDialog* self, QShowEvent* param1);
void KFindDialog_SetVisible(KFindDialog* self, bool visible);
void KFindDialog_OnSetVisible(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseSetVisible(KFindDialog* self, bool visible);
QSize* KFindDialog_SizeHint(const KFindDialog* self);
void KFindDialog_OnSizeHint(const KFindDialog* self, intptr_t slot);
QSize* KFindDialog_QBaseSizeHint(const KFindDialog* self);
QSize* KFindDialog_MinimumSizeHint(const KFindDialog* self);
void KFindDialog_OnMinimumSizeHint(const KFindDialog* self, intptr_t slot);
QSize* KFindDialog_QBaseMinimumSizeHint(const KFindDialog* self);
void KFindDialog_Open(KFindDialog* self);
void KFindDialog_OnOpen(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseOpen(KFindDialog* self);
int KFindDialog_Exec(KFindDialog* self);
void KFindDialog_OnExec(KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseExec(KFindDialog* self);
void KFindDialog_Done(KFindDialog* self, int param1);
void KFindDialog_OnDone(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDone(KFindDialog* self, int param1);
void KFindDialog_Accept(KFindDialog* self);
void KFindDialog_OnAccept(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseAccept(KFindDialog* self);
void KFindDialog_Reject(KFindDialog* self);
void KFindDialog_OnReject(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseReject(KFindDialog* self);
void KFindDialog_KeyPressEvent(KFindDialog* self, QKeyEvent* param1);
void KFindDialog_OnKeyPressEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseKeyPressEvent(KFindDialog* self, QKeyEvent* param1);
void KFindDialog_CloseEvent(KFindDialog* self, QCloseEvent* param1);
void KFindDialog_OnCloseEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseCloseEvent(KFindDialog* self, QCloseEvent* param1);
void KFindDialog_ResizeEvent(KFindDialog* self, QResizeEvent* param1);
void KFindDialog_OnResizeEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseResizeEvent(KFindDialog* self, QResizeEvent* param1);
void KFindDialog_ContextMenuEvent(KFindDialog* self, QContextMenuEvent* param1);
void KFindDialog_OnContextMenuEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseContextMenuEvent(KFindDialog* self, QContextMenuEvent* param1);
bool KFindDialog_EventFilter(KFindDialog* self, QObject* param1, QEvent* param2);
void KFindDialog_OnEventFilter(KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseEventFilter(KFindDialog* self, QObject* param1, QEvent* param2);
int KFindDialog_DevType(const KFindDialog* self);
void KFindDialog_OnDevType(const KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseDevType(const KFindDialog* self);
int KFindDialog_HeightForWidth(const KFindDialog* self, int param1);
void KFindDialog_OnHeightForWidth(const KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseHeightForWidth(const KFindDialog* self, int param1);
bool KFindDialog_HasHeightForWidth(const KFindDialog* self);
void KFindDialog_OnHasHeightForWidth(const KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseHasHeightForWidth(const KFindDialog* self);
QPaintEngine* KFindDialog_PaintEngine(const KFindDialog* self);
void KFindDialog_OnPaintEngine(const KFindDialog* self, intptr_t slot);
QPaintEngine* KFindDialog_QBasePaintEngine(const KFindDialog* self);
bool KFindDialog_Event(KFindDialog* self, QEvent* event);
void KFindDialog_OnEvent(KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseEvent(KFindDialog* self, QEvent* event);
void KFindDialog_MousePressEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_OnMousePressEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseMousePressEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_MouseReleaseEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_OnMouseReleaseEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseMouseReleaseEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_MouseDoubleClickEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_OnMouseDoubleClickEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseMouseDoubleClickEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_MouseMoveEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_OnMouseMoveEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseMouseMoveEvent(KFindDialog* self, QMouseEvent* event);
void KFindDialog_WheelEvent(KFindDialog* self, QWheelEvent* event);
void KFindDialog_OnWheelEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseWheelEvent(KFindDialog* self, QWheelEvent* event);
void KFindDialog_KeyReleaseEvent(KFindDialog* self, QKeyEvent* event);
void KFindDialog_OnKeyReleaseEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseKeyReleaseEvent(KFindDialog* self, QKeyEvent* event);
void KFindDialog_FocusInEvent(KFindDialog* self, QFocusEvent* event);
void KFindDialog_OnFocusInEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseFocusInEvent(KFindDialog* self, QFocusEvent* event);
void KFindDialog_FocusOutEvent(KFindDialog* self, QFocusEvent* event);
void KFindDialog_OnFocusOutEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseFocusOutEvent(KFindDialog* self, QFocusEvent* event);
void KFindDialog_EnterEvent(KFindDialog* self, QEnterEvent* event);
void KFindDialog_OnEnterEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseEnterEvent(KFindDialog* self, QEnterEvent* event);
void KFindDialog_LeaveEvent(KFindDialog* self, QEvent* event);
void KFindDialog_OnLeaveEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseLeaveEvent(KFindDialog* self, QEvent* event);
void KFindDialog_PaintEvent(KFindDialog* self, QPaintEvent* event);
void KFindDialog_OnPaintEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBasePaintEvent(KFindDialog* self, QPaintEvent* event);
void KFindDialog_MoveEvent(KFindDialog* self, QMoveEvent* event);
void KFindDialog_OnMoveEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseMoveEvent(KFindDialog* self, QMoveEvent* event);
void KFindDialog_TabletEvent(KFindDialog* self, QTabletEvent* event);
void KFindDialog_OnTabletEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseTabletEvent(KFindDialog* self, QTabletEvent* event);
void KFindDialog_ActionEvent(KFindDialog* self, QActionEvent* event);
void KFindDialog_OnActionEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseActionEvent(KFindDialog* self, QActionEvent* event);
void KFindDialog_DragEnterEvent(KFindDialog* self, QDragEnterEvent* event);
void KFindDialog_OnDragEnterEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDragEnterEvent(KFindDialog* self, QDragEnterEvent* event);
void KFindDialog_DragMoveEvent(KFindDialog* self, QDragMoveEvent* event);
void KFindDialog_OnDragMoveEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDragMoveEvent(KFindDialog* self, QDragMoveEvent* event);
void KFindDialog_DragLeaveEvent(KFindDialog* self, QDragLeaveEvent* event);
void KFindDialog_OnDragLeaveEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDragLeaveEvent(KFindDialog* self, QDragLeaveEvent* event);
void KFindDialog_DropEvent(KFindDialog* self, QDropEvent* event);
void KFindDialog_OnDropEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDropEvent(KFindDialog* self, QDropEvent* event);
void KFindDialog_HideEvent(KFindDialog* self, QHideEvent* event);
void KFindDialog_OnHideEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseHideEvent(KFindDialog* self, QHideEvent* event);
bool KFindDialog_NativeEvent(KFindDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KFindDialog_OnNativeEvent(KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseNativeEvent(KFindDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KFindDialog_ChangeEvent(KFindDialog* self, QEvent* param1);
void KFindDialog_OnChangeEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseChangeEvent(KFindDialog* self, QEvent* param1);
int KFindDialog_Metric(const KFindDialog* self, int param1);
void KFindDialog_OnMetric(const KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseMetric(const KFindDialog* self, int param1);
void KFindDialog_InitPainter(const KFindDialog* self, QPainter* painter);
void KFindDialog_OnInitPainter(const KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseInitPainter(const KFindDialog* self, QPainter* painter);
QPaintDevice* KFindDialog_Redirected(const KFindDialog* self, QPoint* offset);
void KFindDialog_OnRedirected(const KFindDialog* self, intptr_t slot);
QPaintDevice* KFindDialog_QBaseRedirected(const KFindDialog* self, QPoint* offset);
QPainter* KFindDialog_SharedPainter(const KFindDialog* self);
void KFindDialog_OnSharedPainter(const KFindDialog* self, intptr_t slot);
QPainter* KFindDialog_QBaseSharedPainter(const KFindDialog* self);
void KFindDialog_InputMethodEvent(KFindDialog* self, QInputMethodEvent* param1);
void KFindDialog_OnInputMethodEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseInputMethodEvent(KFindDialog* self, QInputMethodEvent* param1);
QVariant* KFindDialog_InputMethodQuery(const KFindDialog* self, int param1);
void KFindDialog_OnInputMethodQuery(const KFindDialog* self, intptr_t slot);
QVariant* KFindDialog_QBaseInputMethodQuery(const KFindDialog* self, int param1);
bool KFindDialog_FocusNextPrevChild(KFindDialog* self, bool next);
void KFindDialog_OnFocusNextPrevChild(KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseFocusNextPrevChild(KFindDialog* self, bool next);
void KFindDialog_TimerEvent(KFindDialog* self, QTimerEvent* event);
void KFindDialog_OnTimerEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseTimerEvent(KFindDialog* self, QTimerEvent* event);
void KFindDialog_ChildEvent(KFindDialog* self, QChildEvent* event);
void KFindDialog_OnChildEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseChildEvent(KFindDialog* self, QChildEvent* event);
void KFindDialog_CustomEvent(KFindDialog* self, QEvent* event);
void KFindDialog_OnCustomEvent(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseCustomEvent(KFindDialog* self, QEvent* event);
void KFindDialog_ConnectNotify(KFindDialog* self, const QMetaMethod* signal);
void KFindDialog_OnConnectNotify(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseConnectNotify(KFindDialog* self, const QMetaMethod* signal);
void KFindDialog_DisconnectNotify(KFindDialog* self, const QMetaMethod* signal);
void KFindDialog_OnDisconnectNotify(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDisconnectNotify(KFindDialog* self, const QMetaMethod* signal);
void KFindDialog_AdjustPosition(KFindDialog* self, QWidget* param1);
void KFindDialog_OnAdjustPosition(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseAdjustPosition(KFindDialog* self, QWidget* param1);
void KFindDialog_UpdateMicroFocus(KFindDialog* self);
void KFindDialog_OnUpdateMicroFocus(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseUpdateMicroFocus(KFindDialog* self);
void KFindDialog_Create(KFindDialog* self);
void KFindDialog_OnCreate(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseCreate(KFindDialog* self);
void KFindDialog_Destroy(KFindDialog* self);
void KFindDialog_OnDestroy(KFindDialog* self, intptr_t slot);
void KFindDialog_QBaseDestroy(KFindDialog* self);
bool KFindDialog_FocusNextChild(KFindDialog* self);
void KFindDialog_OnFocusNextChild(KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseFocusNextChild(KFindDialog* self);
bool KFindDialog_FocusPreviousChild(KFindDialog* self);
void KFindDialog_OnFocusPreviousChild(KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseFocusPreviousChild(KFindDialog* self);
QObject* KFindDialog_Sender(const KFindDialog* self);
void KFindDialog_OnSender(const KFindDialog* self, intptr_t slot);
QObject* KFindDialog_QBaseSender(const KFindDialog* self);
int KFindDialog_SenderSignalIndex(const KFindDialog* self);
void KFindDialog_OnSenderSignalIndex(const KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseSenderSignalIndex(const KFindDialog* self);
int KFindDialog_Receivers(const KFindDialog* self, const char* signal);
void KFindDialog_OnReceivers(const KFindDialog* self, intptr_t slot);
int KFindDialog_QBaseReceivers(const KFindDialog* self, const char* signal);
bool KFindDialog_IsSignalConnected(const KFindDialog* self, const QMetaMethod* signal);
void KFindDialog_OnIsSignalConnected(const KFindDialog* self, intptr_t slot);
bool KFindDialog_QBaseIsSignalConnected(const KFindDialog* self, const QMetaMethod* signal);
double KFindDialog_GetDecodedMetricF(const KFindDialog* self, int metricA, int metricB);
void KFindDialog_OnGetDecodedMetricF(const KFindDialog* self, intptr_t slot);
double KFindDialog_QBaseGetDecodedMetricF(const KFindDialog* self, int metricA, int metricB);
void KFindDialog_Delete(KFindDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
