#pragma once
#ifndef SRC_EXTRAS_KXMLGUIC_LIBKTOOLBAR_H
#define SRC_EXTRAS_KXMLGUIC_LIBKTOOLBAR_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KConfigGroup KConfigGroup;
typedef struct KMainWindow KMainWindow;
typedef struct KToolBar KToolBar;
typedef struct KXMLGUIClient KXMLGUIClient;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDomElement QDomElement;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMainWindow QMainWindow;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionToolBar QStyleOptionToolBar;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QToolBar QToolBar;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KToolBar* KToolBar_new(QWidget* parent);
KToolBar* KToolBar_new2(const libqt_string objectName, QWidget* parent);
KToolBar* KToolBar_new3(const libqt_string objectName, QMainWindow* parentWindow, int area);
KToolBar* KToolBar_new4(QWidget* parent, bool isMainToolBar);
KToolBar* KToolBar_new5(QWidget* parent, bool isMainToolBar, bool readConfig);
KToolBar* KToolBar_new6(const libqt_string objectName, QWidget* parent, bool readConfig);
KToolBar* KToolBar_new7(const libqt_string objectName, QMainWindow* parentWindow, int area, bool newLine);
KToolBar* KToolBar_new8(const libqt_string objectName, QMainWindow* parentWindow, int area, bool newLine, bool isMainToolBar);
KToolBar* KToolBar_new9(const libqt_string objectName, QMainWindow* parentWindow, int area, bool newLine, bool isMainToolBar, bool readConfig);
QMetaObject* KToolBar_MetaObject(const KToolBar* self);
void* KToolBar_Metacast(KToolBar* self, const char* param1);
int KToolBar_Metacall(KToolBar* self, int param1, int param2, void** param3);
libqt_string KToolBar_Tr(const char* s);
KMainWindow* KToolBar_MainWindow(const KToolBar* self);
void KToolBar_SetIconDimensions(KToolBar* self, int size);
int KToolBar_IconSizeDefault(const KToolBar* self);
void KToolBar_SaveSettings(KToolBar* self, KConfigGroup* cg);
void KToolBar_ApplySettings(KToolBar* self, const KConfigGroup* cg);
void KToolBar_AddXMLGUIClient(KToolBar* self, KXMLGUIClient* client);
void KToolBar_RemoveXMLGUIClient(KToolBar* self, KXMLGUIClient* client);
void KToolBar_LoadState(KToolBar* self, const QDomElement* element);
void KToolBar_SaveState(const KToolBar* self, QDomElement* element);
bool KToolBar_EventFilter(KToolBar* self, QObject* watched, QEvent* event);
bool KToolBar_ToolBarsEditable();
void KToolBar_SetToolBarsEditable(bool editable);
bool KToolBar_ToolBarsLocked();
void KToolBar_SetToolBarsLocked(bool locked);
void KToolBar_EmitToolbarStyleChanged();
void KToolBar_SlotMovableChanged(KToolBar* self, bool movable);
void KToolBar_ContextMenuEvent(KToolBar* self, QContextMenuEvent* param1);
void KToolBar_ActionEvent(KToolBar* self, QActionEvent* param1);
void KToolBar_DragEnterEvent(KToolBar* self, QDragEnterEvent* param1);
void KToolBar_DragMoveEvent(KToolBar* self, QDragMoveEvent* param1);
void KToolBar_DragLeaveEvent(KToolBar* self, QDragLeaveEvent* param1);
void KToolBar_DropEvent(KToolBar* self, QDropEvent* param1);
void KToolBar_MousePressEvent(KToolBar* self, QMouseEvent* param1);
void KToolBar_MouseMoveEvent(KToolBar* self, QMouseEvent* param1);
void KToolBar_MouseReleaseEvent(KToolBar* self, QMouseEvent* param1);
libqt_string KToolBar_Tr2(const char* s, const char* c);
libqt_string KToolBar_Tr3(const char* s, const char* c, int n);
void KToolBar_OnMetacall(KToolBar* self, intptr_t slot);
int KToolBar_QBaseMetacall(KToolBar* self, int param1, int param2, void** param3);
void KToolBar_OnEventFilter(KToolBar* self, intptr_t slot);
bool KToolBar_QBaseEventFilter(KToolBar* self, QObject* watched, QEvent* event);
void KToolBar_OnSlotMovableChanged(KToolBar* self, intptr_t slot);
void KToolBar_QBaseSlotMovableChanged(KToolBar* self, bool movable);
void KToolBar_OnContextMenuEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseContextMenuEvent(KToolBar* self, QContextMenuEvent* param1);
void KToolBar_OnActionEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseActionEvent(KToolBar* self, QActionEvent* param1);
void KToolBar_OnDragEnterEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseDragEnterEvent(KToolBar* self, QDragEnterEvent* param1);
void KToolBar_OnDragMoveEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseDragMoveEvent(KToolBar* self, QDragMoveEvent* param1);
void KToolBar_OnDragLeaveEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseDragLeaveEvent(KToolBar* self, QDragLeaveEvent* param1);
void KToolBar_OnDropEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseDropEvent(KToolBar* self, QDropEvent* param1);
void KToolBar_OnMousePressEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseMousePressEvent(KToolBar* self, QMouseEvent* param1);
void KToolBar_OnMouseMoveEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseMouseMoveEvent(KToolBar* self, QMouseEvent* param1);
void KToolBar_OnMouseReleaseEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseMouseReleaseEvent(KToolBar* self, QMouseEvent* param1);
void KToolBar_ChangeEvent(KToolBar* self, QEvent* event);
void KToolBar_OnChangeEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseChangeEvent(KToolBar* self, QEvent* event);
void KToolBar_PaintEvent(KToolBar* self, QPaintEvent* event);
void KToolBar_OnPaintEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBasePaintEvent(KToolBar* self, QPaintEvent* event);
bool KToolBar_Event(KToolBar* self, QEvent* event);
void KToolBar_OnEvent(KToolBar* self, intptr_t slot);
bool KToolBar_QBaseEvent(KToolBar* self, QEvent* event);
void KToolBar_InitStyleOption(const KToolBar* self, QStyleOptionToolBar* option);
void KToolBar_OnInitStyleOption(const KToolBar* self, intptr_t slot);
void KToolBar_QBaseInitStyleOption(const KToolBar* self, QStyleOptionToolBar* option);
int KToolBar_DevType(const KToolBar* self);
void KToolBar_OnDevType(const KToolBar* self, intptr_t slot);
int KToolBar_QBaseDevType(const KToolBar* self);
void KToolBar_SetVisible(KToolBar* self, bool visible);
void KToolBar_OnSetVisible(KToolBar* self, intptr_t slot);
void KToolBar_QBaseSetVisible(KToolBar* self, bool visible);
QSize* KToolBar_SizeHint(const KToolBar* self);
void KToolBar_OnSizeHint(const KToolBar* self, intptr_t slot);
QSize* KToolBar_QBaseSizeHint(const KToolBar* self);
QSize* KToolBar_MinimumSizeHint(const KToolBar* self);
void KToolBar_OnMinimumSizeHint(const KToolBar* self, intptr_t slot);
QSize* KToolBar_QBaseMinimumSizeHint(const KToolBar* self);
int KToolBar_HeightForWidth(const KToolBar* self, int param1);
void KToolBar_OnHeightForWidth(const KToolBar* self, intptr_t slot);
int KToolBar_QBaseHeightForWidth(const KToolBar* self, int param1);
bool KToolBar_HasHeightForWidth(const KToolBar* self);
void KToolBar_OnHasHeightForWidth(const KToolBar* self, intptr_t slot);
bool KToolBar_QBaseHasHeightForWidth(const KToolBar* self);
QPaintEngine* KToolBar_PaintEngine(const KToolBar* self);
void KToolBar_OnPaintEngine(const KToolBar* self, intptr_t slot);
QPaintEngine* KToolBar_QBasePaintEngine(const KToolBar* self);
void KToolBar_MouseDoubleClickEvent(KToolBar* self, QMouseEvent* event);
void KToolBar_OnMouseDoubleClickEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseMouseDoubleClickEvent(KToolBar* self, QMouseEvent* event);
void KToolBar_WheelEvent(KToolBar* self, QWheelEvent* event);
void KToolBar_OnWheelEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseWheelEvent(KToolBar* self, QWheelEvent* event);
void KToolBar_KeyPressEvent(KToolBar* self, QKeyEvent* event);
void KToolBar_OnKeyPressEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseKeyPressEvent(KToolBar* self, QKeyEvent* event);
void KToolBar_KeyReleaseEvent(KToolBar* self, QKeyEvent* event);
void KToolBar_OnKeyReleaseEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseKeyReleaseEvent(KToolBar* self, QKeyEvent* event);
void KToolBar_FocusInEvent(KToolBar* self, QFocusEvent* event);
void KToolBar_OnFocusInEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseFocusInEvent(KToolBar* self, QFocusEvent* event);
void KToolBar_FocusOutEvent(KToolBar* self, QFocusEvent* event);
void KToolBar_OnFocusOutEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseFocusOutEvent(KToolBar* self, QFocusEvent* event);
void KToolBar_EnterEvent(KToolBar* self, QEnterEvent* event);
void KToolBar_OnEnterEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseEnterEvent(KToolBar* self, QEnterEvent* event);
void KToolBar_LeaveEvent(KToolBar* self, QEvent* event);
void KToolBar_OnLeaveEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseLeaveEvent(KToolBar* self, QEvent* event);
void KToolBar_MoveEvent(KToolBar* self, QMoveEvent* event);
void KToolBar_OnMoveEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseMoveEvent(KToolBar* self, QMoveEvent* event);
void KToolBar_ResizeEvent(KToolBar* self, QResizeEvent* event);
void KToolBar_OnResizeEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseResizeEvent(KToolBar* self, QResizeEvent* event);
void KToolBar_CloseEvent(KToolBar* self, QCloseEvent* event);
void KToolBar_OnCloseEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseCloseEvent(KToolBar* self, QCloseEvent* event);
void KToolBar_TabletEvent(KToolBar* self, QTabletEvent* event);
void KToolBar_OnTabletEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseTabletEvent(KToolBar* self, QTabletEvent* event);
void KToolBar_ShowEvent(KToolBar* self, QShowEvent* event);
void KToolBar_OnShowEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseShowEvent(KToolBar* self, QShowEvent* event);
void KToolBar_HideEvent(KToolBar* self, QHideEvent* event);
void KToolBar_OnHideEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseHideEvent(KToolBar* self, QHideEvent* event);
bool KToolBar_NativeEvent(KToolBar* self, const libqt_string eventType, void* message, intptr_t* result);
void KToolBar_OnNativeEvent(KToolBar* self, intptr_t slot);
bool KToolBar_QBaseNativeEvent(KToolBar* self, const libqt_string eventType, void* message, intptr_t* result);
int KToolBar_Metric(const KToolBar* self, int param1);
void KToolBar_OnMetric(const KToolBar* self, intptr_t slot);
int KToolBar_QBaseMetric(const KToolBar* self, int param1);
void KToolBar_InitPainter(const KToolBar* self, QPainter* painter);
void KToolBar_OnInitPainter(const KToolBar* self, intptr_t slot);
void KToolBar_QBaseInitPainter(const KToolBar* self, QPainter* painter);
QPaintDevice* KToolBar_Redirected(const KToolBar* self, QPoint* offset);
void KToolBar_OnRedirected(const KToolBar* self, intptr_t slot);
QPaintDevice* KToolBar_QBaseRedirected(const KToolBar* self, QPoint* offset);
QPainter* KToolBar_SharedPainter(const KToolBar* self);
void KToolBar_OnSharedPainter(const KToolBar* self, intptr_t slot);
QPainter* KToolBar_QBaseSharedPainter(const KToolBar* self);
void KToolBar_InputMethodEvent(KToolBar* self, QInputMethodEvent* param1);
void KToolBar_OnInputMethodEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseInputMethodEvent(KToolBar* self, QInputMethodEvent* param1);
QVariant* KToolBar_InputMethodQuery(const KToolBar* self, int param1);
void KToolBar_OnInputMethodQuery(const KToolBar* self, intptr_t slot);
QVariant* KToolBar_QBaseInputMethodQuery(const KToolBar* self, int param1);
bool KToolBar_FocusNextPrevChild(KToolBar* self, bool next);
void KToolBar_OnFocusNextPrevChild(KToolBar* self, intptr_t slot);
bool KToolBar_QBaseFocusNextPrevChild(KToolBar* self, bool next);
void KToolBar_TimerEvent(KToolBar* self, QTimerEvent* event);
void KToolBar_OnTimerEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseTimerEvent(KToolBar* self, QTimerEvent* event);
void KToolBar_ChildEvent(KToolBar* self, QChildEvent* event);
void KToolBar_OnChildEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseChildEvent(KToolBar* self, QChildEvent* event);
void KToolBar_CustomEvent(KToolBar* self, QEvent* event);
void KToolBar_OnCustomEvent(KToolBar* self, intptr_t slot);
void KToolBar_QBaseCustomEvent(KToolBar* self, QEvent* event);
void KToolBar_ConnectNotify(KToolBar* self, const QMetaMethod* signal);
void KToolBar_OnConnectNotify(KToolBar* self, intptr_t slot);
void KToolBar_QBaseConnectNotify(KToolBar* self, const QMetaMethod* signal);
void KToolBar_DisconnectNotify(KToolBar* self, const QMetaMethod* signal);
void KToolBar_OnDisconnectNotify(KToolBar* self, intptr_t slot);
void KToolBar_QBaseDisconnectNotify(KToolBar* self, const QMetaMethod* signal);
void KToolBar_UpdateMicroFocus(KToolBar* self);
void KToolBar_OnUpdateMicroFocus(KToolBar* self, intptr_t slot);
void KToolBar_QBaseUpdateMicroFocus(KToolBar* self);
void KToolBar_Create(KToolBar* self);
void KToolBar_OnCreate(KToolBar* self, intptr_t slot);
void KToolBar_QBaseCreate(KToolBar* self);
void KToolBar_Destroy(KToolBar* self);
void KToolBar_OnDestroy(KToolBar* self, intptr_t slot);
void KToolBar_QBaseDestroy(KToolBar* self);
bool KToolBar_FocusNextChild(KToolBar* self);
void KToolBar_OnFocusNextChild(KToolBar* self, intptr_t slot);
bool KToolBar_QBaseFocusNextChild(KToolBar* self);
bool KToolBar_FocusPreviousChild(KToolBar* self);
void KToolBar_OnFocusPreviousChild(KToolBar* self, intptr_t slot);
bool KToolBar_QBaseFocusPreviousChild(KToolBar* self);
QObject* KToolBar_Sender(const KToolBar* self);
void KToolBar_OnSender(const KToolBar* self, intptr_t slot);
QObject* KToolBar_QBaseSender(const KToolBar* self);
int KToolBar_SenderSignalIndex(const KToolBar* self);
void KToolBar_OnSenderSignalIndex(const KToolBar* self, intptr_t slot);
int KToolBar_QBaseSenderSignalIndex(const KToolBar* self);
int KToolBar_Receivers(const KToolBar* self, const char* signal);
void KToolBar_OnReceivers(const KToolBar* self, intptr_t slot);
int KToolBar_QBaseReceivers(const KToolBar* self, const char* signal);
bool KToolBar_IsSignalConnected(const KToolBar* self, const QMetaMethod* signal);
void KToolBar_OnIsSignalConnected(const KToolBar* self, intptr_t slot);
bool KToolBar_QBaseIsSignalConnected(const KToolBar* self, const QMetaMethod* signal);
double KToolBar_GetDecodedMetricF(const KToolBar* self, int metricA, int metricB);
void KToolBar_OnGetDecodedMetricF(const KToolBar* self, intptr_t slot);
double KToolBar_QBaseGetDecodedMetricF(const KToolBar* self, int metricA, int metricB);
void KToolBar_Delete(KToolBar* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
