#pragma once
#ifndef SRCC_LIBQDATETIMEEDIT_H
#define SRCC_LIBQDATETIMEEDIT_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractSpinBox QAbstractSpinBox;
typedef struct QActionEvent QActionEvent;
typedef struct QCalendar QCalendar;
typedef struct QCalendarWidget QCalendarWidget;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDate QDate;
typedef struct QDateEdit QDateEdit;
typedef struct QDateTime QDateTime;
typedef struct QDateTimeEdit QDateTimeEdit;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionSpinBox QStyleOptionSpinBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTime QTime;
typedef struct QTimeEdit QTimeEdit;
typedef struct QTimeZone QTimeZone;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QDateTimeEdit* QDateTimeEdit_new(QWidget* parent);
QDateTimeEdit* QDateTimeEdit_new2();
QDateTimeEdit* QDateTimeEdit_new3(const QDateTime* dt);
QDateTimeEdit* QDateTimeEdit_new4(QDate* d);
QDateTimeEdit* QDateTimeEdit_new5(QTime* t);
QDateTimeEdit* QDateTimeEdit_new6(const QDateTime* dt, QWidget* parent);
QDateTimeEdit* QDateTimeEdit_new7(QDate* d, QWidget* parent);
QDateTimeEdit* QDateTimeEdit_new8(QTime* t, QWidget* parent);
QMetaObject* QDateTimeEdit_MetaObject(const QDateTimeEdit* self);
void* QDateTimeEdit_Metacast(QDateTimeEdit* self, const char* param1);
int QDateTimeEdit_Metacall(QDateTimeEdit* self, int param1, int param2, void** param3);
libqt_string QDateTimeEdit_Tr(const char* s);
QDateTime* QDateTimeEdit_DateTime(const QDateTimeEdit* self);
QDate* QDateTimeEdit_Date(const QDateTimeEdit* self);
QTime* QDateTimeEdit_Time(const QDateTimeEdit* self);
QCalendar* QDateTimeEdit_Calendar(const QDateTimeEdit* self);
void QDateTimeEdit_SetCalendar(QDateTimeEdit* self, QCalendar* calendar);
QDateTime* QDateTimeEdit_MinimumDateTime(const QDateTimeEdit* self);
void QDateTimeEdit_ClearMinimumDateTime(QDateTimeEdit* self);
void QDateTimeEdit_SetMinimumDateTime(QDateTimeEdit* self, const QDateTime* dt);
QDateTime* QDateTimeEdit_MaximumDateTime(const QDateTimeEdit* self);
void QDateTimeEdit_ClearMaximumDateTime(QDateTimeEdit* self);
void QDateTimeEdit_SetMaximumDateTime(QDateTimeEdit* self, const QDateTime* dt);
void QDateTimeEdit_SetDateTimeRange(QDateTimeEdit* self, const QDateTime* min, const QDateTime* max);
QDate* QDateTimeEdit_MinimumDate(const QDateTimeEdit* self);
void QDateTimeEdit_SetMinimumDate(QDateTimeEdit* self, QDate* min);
void QDateTimeEdit_ClearMinimumDate(QDateTimeEdit* self);
QDate* QDateTimeEdit_MaximumDate(const QDateTimeEdit* self);
void QDateTimeEdit_SetMaximumDate(QDateTimeEdit* self, QDate* max);
void QDateTimeEdit_ClearMaximumDate(QDateTimeEdit* self);
void QDateTimeEdit_SetDateRange(QDateTimeEdit* self, QDate* min, QDate* max);
QTime* QDateTimeEdit_MinimumTime(const QDateTimeEdit* self);
void QDateTimeEdit_SetMinimumTime(QDateTimeEdit* self, QTime* min);
void QDateTimeEdit_ClearMinimumTime(QDateTimeEdit* self);
QTime* QDateTimeEdit_MaximumTime(const QDateTimeEdit* self);
void QDateTimeEdit_SetMaximumTime(QDateTimeEdit* self, QTime* max);
void QDateTimeEdit_ClearMaximumTime(QDateTimeEdit* self);
void QDateTimeEdit_SetTimeRange(QDateTimeEdit* self, QTime* min, QTime* max);
int QDateTimeEdit_DisplayedSections(const QDateTimeEdit* self);
int QDateTimeEdit_CurrentSection(const QDateTimeEdit* self);
int QDateTimeEdit_SectionAt(const QDateTimeEdit* self, int index);
void QDateTimeEdit_SetCurrentSection(QDateTimeEdit* self, int section);
int QDateTimeEdit_CurrentSectionIndex(const QDateTimeEdit* self);
void QDateTimeEdit_SetCurrentSectionIndex(QDateTimeEdit* self, int index);
QCalendarWidget* QDateTimeEdit_CalendarWidget(const QDateTimeEdit* self);
void QDateTimeEdit_SetCalendarWidget(QDateTimeEdit* self, QCalendarWidget* calendarWidget);
int QDateTimeEdit_SectionCount(const QDateTimeEdit* self);
void QDateTimeEdit_SetSelectedSection(QDateTimeEdit* self, int section);
libqt_string QDateTimeEdit_SectionText(const QDateTimeEdit* self, int section);
libqt_string QDateTimeEdit_DisplayFormat(const QDateTimeEdit* self);
void QDateTimeEdit_SetDisplayFormat(QDateTimeEdit* self, const libqt_string format);
bool QDateTimeEdit_CalendarPopup(const QDateTimeEdit* self);
void QDateTimeEdit_SetCalendarPopup(QDateTimeEdit* self, bool enable);
int QDateTimeEdit_TimeSpec(const QDateTimeEdit* self);
void QDateTimeEdit_SetTimeSpec(QDateTimeEdit* self, int spec);
QTimeZone* QDateTimeEdit_TimeZone(const QDateTimeEdit* self);
void QDateTimeEdit_SetTimeZone(QDateTimeEdit* self, const QTimeZone* zone);
QSize* QDateTimeEdit_SizeHint(const QDateTimeEdit* self);
void QDateTimeEdit_Clear(QDateTimeEdit* self);
void QDateTimeEdit_StepBy(QDateTimeEdit* self, int steps);
bool QDateTimeEdit_Event(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_DateTimeChanged(QDateTimeEdit* self, const QDateTime* dateTime);
void QDateTimeEdit_Connect_DateTimeChanged(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_TimeChanged(QDateTimeEdit* self, QTime* time);
void QDateTimeEdit_Connect_TimeChanged(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_DateChanged(QDateTimeEdit* self, QDate* date);
void QDateTimeEdit_Connect_DateChanged(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_SetDateTime(QDateTimeEdit* self, const QDateTime* dateTime);
void QDateTimeEdit_SetDate(QDateTimeEdit* self, QDate* date);
void QDateTimeEdit_SetTime(QDateTimeEdit* self, QTime* time);
void QDateTimeEdit_KeyPressEvent(QDateTimeEdit* self, QKeyEvent* event);
void QDateTimeEdit_WheelEvent(QDateTimeEdit* self, QWheelEvent* event);
void QDateTimeEdit_FocusInEvent(QDateTimeEdit* self, QFocusEvent* event);
bool QDateTimeEdit_FocusNextPrevChild(QDateTimeEdit* self, bool next);
int QDateTimeEdit_Validate(const QDateTimeEdit* self, libqt_string input, int* pos);
void QDateTimeEdit_Fixup(const QDateTimeEdit* self, libqt_string input);
QDateTime* QDateTimeEdit_DateTimeFromText(const QDateTimeEdit* self, const libqt_string text);
libqt_string QDateTimeEdit_TextFromDateTime(const QDateTimeEdit* self, const QDateTime* dt);
int QDateTimeEdit_StepEnabled(const QDateTimeEdit* self);
void QDateTimeEdit_MousePressEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_PaintEvent(QDateTimeEdit* self, QPaintEvent* event);
void QDateTimeEdit_InitStyleOption(const QDateTimeEdit* self, QStyleOptionSpinBox* option);
libqt_string QDateTimeEdit_Tr2(const char* s, const char* c);
libqt_string QDateTimeEdit_Tr3(const char* s, const char* c, int n);
void QDateTimeEdit_OnMetacall(QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseMetacall(QDateTimeEdit* self, int param1, int param2, void** param3);
void QDateTimeEdit_OnSizeHint(const QDateTimeEdit* self, intptr_t slot);
QSize* QDateTimeEdit_QBaseSizeHint(const QDateTimeEdit* self);
void QDateTimeEdit_OnClear(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseClear(QDateTimeEdit* self);
void QDateTimeEdit_OnStepBy(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseStepBy(QDateTimeEdit* self, int steps);
void QDateTimeEdit_OnEvent(QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_OnKeyPressEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseKeyPressEvent(QDateTimeEdit* self, QKeyEvent* event);
void QDateTimeEdit_OnWheelEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseWheelEvent(QDateTimeEdit* self, QWheelEvent* event);
void QDateTimeEdit_OnFocusInEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseFocusInEvent(QDateTimeEdit* self, QFocusEvent* event);
void QDateTimeEdit_OnFocusNextPrevChild(QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseFocusNextPrevChild(QDateTimeEdit* self, bool next);
void QDateTimeEdit_OnValidate(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseValidate(const QDateTimeEdit* self, libqt_string input, int* pos);
void QDateTimeEdit_OnFixup(const QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseFixup(const QDateTimeEdit* self, libqt_string input);
void QDateTimeEdit_OnDateTimeFromText(const QDateTimeEdit* self, intptr_t slot);
QDateTime* QDateTimeEdit_QBaseDateTimeFromText(const QDateTimeEdit* self, const libqt_string text);
void QDateTimeEdit_OnTextFromDateTime(const QDateTimeEdit* self, intptr_t slot);
libqt_string QDateTimeEdit_QBaseTextFromDateTime(const QDateTimeEdit* self, const QDateTime* dt);
void QDateTimeEdit_OnStepEnabled(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseStepEnabled(const QDateTimeEdit* self);
void QDateTimeEdit_OnMousePressEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseMousePressEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_OnPaintEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBasePaintEvent(QDateTimeEdit* self, QPaintEvent* event);
void QDateTimeEdit_OnInitStyleOption(const QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseInitStyleOption(const QDateTimeEdit* self, QStyleOptionSpinBox* option);
QSize* QDateTimeEdit_MinimumSizeHint(const QDateTimeEdit* self);
void QDateTimeEdit_OnMinimumSizeHint(const QDateTimeEdit* self, intptr_t slot);
QSize* QDateTimeEdit_QBaseMinimumSizeHint(const QDateTimeEdit* self);
QVariant* QDateTimeEdit_InputMethodQuery(const QDateTimeEdit* self, int param1);
void QDateTimeEdit_OnInputMethodQuery(const QDateTimeEdit* self, intptr_t slot);
QVariant* QDateTimeEdit_QBaseInputMethodQuery(const QDateTimeEdit* self, int param1);
void QDateTimeEdit_ResizeEvent(QDateTimeEdit* self, QResizeEvent* event);
void QDateTimeEdit_OnResizeEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseResizeEvent(QDateTimeEdit* self, QResizeEvent* event);
void QDateTimeEdit_KeyReleaseEvent(QDateTimeEdit* self, QKeyEvent* event);
void QDateTimeEdit_OnKeyReleaseEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseKeyReleaseEvent(QDateTimeEdit* self, QKeyEvent* event);
void QDateTimeEdit_FocusOutEvent(QDateTimeEdit* self, QFocusEvent* event);
void QDateTimeEdit_OnFocusOutEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseFocusOutEvent(QDateTimeEdit* self, QFocusEvent* event);
void QDateTimeEdit_ContextMenuEvent(QDateTimeEdit* self, QContextMenuEvent* event);
void QDateTimeEdit_OnContextMenuEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseContextMenuEvent(QDateTimeEdit* self, QContextMenuEvent* event);
void QDateTimeEdit_ChangeEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_OnChangeEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseChangeEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_CloseEvent(QDateTimeEdit* self, QCloseEvent* event);
void QDateTimeEdit_OnCloseEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseCloseEvent(QDateTimeEdit* self, QCloseEvent* event);
void QDateTimeEdit_HideEvent(QDateTimeEdit* self, QHideEvent* event);
void QDateTimeEdit_OnHideEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseHideEvent(QDateTimeEdit* self, QHideEvent* event);
void QDateTimeEdit_MouseReleaseEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_OnMouseReleaseEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseMouseReleaseEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_MouseMoveEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_OnMouseMoveEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseMouseMoveEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_TimerEvent(QDateTimeEdit* self, QTimerEvent* event);
void QDateTimeEdit_OnTimerEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseTimerEvent(QDateTimeEdit* self, QTimerEvent* event);
void QDateTimeEdit_ShowEvent(QDateTimeEdit* self, QShowEvent* event);
void QDateTimeEdit_OnShowEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseShowEvent(QDateTimeEdit* self, QShowEvent* event);
int QDateTimeEdit_DevType(const QDateTimeEdit* self);
void QDateTimeEdit_OnDevType(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseDevType(const QDateTimeEdit* self);
void QDateTimeEdit_SetVisible(QDateTimeEdit* self, bool visible);
void QDateTimeEdit_OnSetVisible(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseSetVisible(QDateTimeEdit* self, bool visible);
int QDateTimeEdit_HeightForWidth(const QDateTimeEdit* self, int param1);
void QDateTimeEdit_OnHeightForWidth(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseHeightForWidth(const QDateTimeEdit* self, int param1);
bool QDateTimeEdit_HasHeightForWidth(const QDateTimeEdit* self);
void QDateTimeEdit_OnHasHeightForWidth(const QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseHasHeightForWidth(const QDateTimeEdit* self);
QPaintEngine* QDateTimeEdit_PaintEngine(const QDateTimeEdit* self);
void QDateTimeEdit_OnPaintEngine(const QDateTimeEdit* self, intptr_t slot);
QPaintEngine* QDateTimeEdit_QBasePaintEngine(const QDateTimeEdit* self);
void QDateTimeEdit_MouseDoubleClickEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_OnMouseDoubleClickEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseMouseDoubleClickEvent(QDateTimeEdit* self, QMouseEvent* event);
void QDateTimeEdit_EnterEvent(QDateTimeEdit* self, QEnterEvent* event);
void QDateTimeEdit_OnEnterEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseEnterEvent(QDateTimeEdit* self, QEnterEvent* event);
void QDateTimeEdit_LeaveEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_OnLeaveEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseLeaveEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_MoveEvent(QDateTimeEdit* self, QMoveEvent* event);
void QDateTimeEdit_OnMoveEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseMoveEvent(QDateTimeEdit* self, QMoveEvent* event);
void QDateTimeEdit_TabletEvent(QDateTimeEdit* self, QTabletEvent* event);
void QDateTimeEdit_OnTabletEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseTabletEvent(QDateTimeEdit* self, QTabletEvent* event);
void QDateTimeEdit_ActionEvent(QDateTimeEdit* self, QActionEvent* event);
void QDateTimeEdit_OnActionEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseActionEvent(QDateTimeEdit* self, QActionEvent* event);
void QDateTimeEdit_DragEnterEvent(QDateTimeEdit* self, QDragEnterEvent* event);
void QDateTimeEdit_OnDragEnterEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseDragEnterEvent(QDateTimeEdit* self, QDragEnterEvent* event);
void QDateTimeEdit_DragMoveEvent(QDateTimeEdit* self, QDragMoveEvent* event);
void QDateTimeEdit_OnDragMoveEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseDragMoveEvent(QDateTimeEdit* self, QDragMoveEvent* event);
void QDateTimeEdit_DragLeaveEvent(QDateTimeEdit* self, QDragLeaveEvent* event);
void QDateTimeEdit_OnDragLeaveEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseDragLeaveEvent(QDateTimeEdit* self, QDragLeaveEvent* event);
void QDateTimeEdit_DropEvent(QDateTimeEdit* self, QDropEvent* event);
void QDateTimeEdit_OnDropEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseDropEvent(QDateTimeEdit* self, QDropEvent* event);
bool QDateTimeEdit_NativeEvent(QDateTimeEdit* self, const libqt_string eventType, void* message, intptr_t* result);
void QDateTimeEdit_OnNativeEvent(QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseNativeEvent(QDateTimeEdit* self, const libqt_string eventType, void* message, intptr_t* result);
int QDateTimeEdit_Metric(const QDateTimeEdit* self, int param1);
void QDateTimeEdit_OnMetric(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseMetric(const QDateTimeEdit* self, int param1);
void QDateTimeEdit_InitPainter(const QDateTimeEdit* self, QPainter* painter);
void QDateTimeEdit_OnInitPainter(const QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseInitPainter(const QDateTimeEdit* self, QPainter* painter);
QPaintDevice* QDateTimeEdit_Redirected(const QDateTimeEdit* self, QPoint* offset);
void QDateTimeEdit_OnRedirected(const QDateTimeEdit* self, intptr_t slot);
QPaintDevice* QDateTimeEdit_QBaseRedirected(const QDateTimeEdit* self, QPoint* offset);
QPainter* QDateTimeEdit_SharedPainter(const QDateTimeEdit* self);
void QDateTimeEdit_OnSharedPainter(const QDateTimeEdit* self, intptr_t slot);
QPainter* QDateTimeEdit_QBaseSharedPainter(const QDateTimeEdit* self);
void QDateTimeEdit_InputMethodEvent(QDateTimeEdit* self, QInputMethodEvent* param1);
void QDateTimeEdit_OnInputMethodEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseInputMethodEvent(QDateTimeEdit* self, QInputMethodEvent* param1);
bool QDateTimeEdit_EventFilter(QDateTimeEdit* self, QObject* watched, QEvent* event);
void QDateTimeEdit_OnEventFilter(QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseEventFilter(QDateTimeEdit* self, QObject* watched, QEvent* event);
void QDateTimeEdit_ChildEvent(QDateTimeEdit* self, QChildEvent* event);
void QDateTimeEdit_OnChildEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseChildEvent(QDateTimeEdit* self, QChildEvent* event);
void QDateTimeEdit_CustomEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_OnCustomEvent(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseCustomEvent(QDateTimeEdit* self, QEvent* event);
void QDateTimeEdit_ConnectNotify(QDateTimeEdit* self, const QMetaMethod* signal);
void QDateTimeEdit_OnConnectNotify(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseConnectNotify(QDateTimeEdit* self, const QMetaMethod* signal);
void QDateTimeEdit_DisconnectNotify(QDateTimeEdit* self, const QMetaMethod* signal);
void QDateTimeEdit_OnDisconnectNotify(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseDisconnectNotify(QDateTimeEdit* self, const QMetaMethod* signal);
QLineEdit* QDateTimeEdit_LineEdit(const QDateTimeEdit* self);
void QDateTimeEdit_OnLineEdit(const QDateTimeEdit* self, intptr_t slot);
QLineEdit* QDateTimeEdit_QBaseLineEdit(const QDateTimeEdit* self);
void QDateTimeEdit_SetLineEdit(QDateTimeEdit* self, QLineEdit* edit);
void QDateTimeEdit_OnSetLineEdit(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseSetLineEdit(QDateTimeEdit* self, QLineEdit* edit);
void QDateTimeEdit_UpdateMicroFocus(QDateTimeEdit* self);
void QDateTimeEdit_OnUpdateMicroFocus(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseUpdateMicroFocus(QDateTimeEdit* self);
void QDateTimeEdit_Create(QDateTimeEdit* self);
void QDateTimeEdit_OnCreate(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseCreate(QDateTimeEdit* self);
void QDateTimeEdit_Destroy(QDateTimeEdit* self);
void QDateTimeEdit_OnDestroy(QDateTimeEdit* self, intptr_t slot);
void QDateTimeEdit_QBaseDestroy(QDateTimeEdit* self);
bool QDateTimeEdit_FocusNextChild(QDateTimeEdit* self);
void QDateTimeEdit_OnFocusNextChild(QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseFocusNextChild(QDateTimeEdit* self);
bool QDateTimeEdit_FocusPreviousChild(QDateTimeEdit* self);
void QDateTimeEdit_OnFocusPreviousChild(QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseFocusPreviousChild(QDateTimeEdit* self);
QObject* QDateTimeEdit_Sender(const QDateTimeEdit* self);
void QDateTimeEdit_OnSender(const QDateTimeEdit* self, intptr_t slot);
QObject* QDateTimeEdit_QBaseSender(const QDateTimeEdit* self);
int QDateTimeEdit_SenderSignalIndex(const QDateTimeEdit* self);
void QDateTimeEdit_OnSenderSignalIndex(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseSenderSignalIndex(const QDateTimeEdit* self);
int QDateTimeEdit_Receivers(const QDateTimeEdit* self, const char* signal);
void QDateTimeEdit_OnReceivers(const QDateTimeEdit* self, intptr_t slot);
int QDateTimeEdit_QBaseReceivers(const QDateTimeEdit* self, const char* signal);
bool QDateTimeEdit_IsSignalConnected(const QDateTimeEdit* self, const QMetaMethod* signal);
void QDateTimeEdit_OnIsSignalConnected(const QDateTimeEdit* self, intptr_t slot);
bool QDateTimeEdit_QBaseIsSignalConnected(const QDateTimeEdit* self, const QMetaMethod* signal);
double QDateTimeEdit_GetDecodedMetricF(const QDateTimeEdit* self, int metricA, int metricB);
void QDateTimeEdit_OnGetDecodedMetricF(const QDateTimeEdit* self, intptr_t slot);
double QDateTimeEdit_QBaseGetDecodedMetricF(const QDateTimeEdit* self, int metricA, int metricB);
void QDateTimeEdit_Delete(QDateTimeEdit* self);

QTimeEdit* QTimeEdit_new(QWidget* parent);
QTimeEdit* QTimeEdit_new2();
QTimeEdit* QTimeEdit_new3(QTime* time);
QTimeEdit* QTimeEdit_new4(QTime* time, QWidget* parent);
QMetaObject* QTimeEdit_MetaObject(const QTimeEdit* self);
void* QTimeEdit_Metacast(QTimeEdit* self, const char* param1);
int QTimeEdit_Metacall(QTimeEdit* self, int param1, int param2, void** param3);
libqt_string QTimeEdit_Tr(const char* s);
void QTimeEdit_UserTimeChanged(QTimeEdit* self, QTime* time);
void QTimeEdit_Connect_UserTimeChanged(QTimeEdit* self, intptr_t slot);
libqt_string QTimeEdit_Tr2(const char* s, const char* c);
libqt_string QTimeEdit_Tr3(const char* s, const char* c, int n);
void QTimeEdit_OnMetacall(QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseMetacall(QTimeEdit* self, int param1, int param2, void** param3);
QSize* QTimeEdit_SizeHint(const QTimeEdit* self);
void QTimeEdit_OnSizeHint(const QTimeEdit* self, intptr_t slot);
QSize* QTimeEdit_QBaseSizeHint(const QTimeEdit* self);
void QTimeEdit_Clear(QTimeEdit* self);
void QTimeEdit_OnClear(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseClear(QTimeEdit* self);
void QTimeEdit_StepBy(QTimeEdit* self, int steps);
void QTimeEdit_OnStepBy(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseStepBy(QTimeEdit* self, int steps);
bool QTimeEdit_Event(QTimeEdit* self, QEvent* event);
void QTimeEdit_OnEvent(QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_KeyPressEvent(QTimeEdit* self, QKeyEvent* event);
void QTimeEdit_OnKeyPressEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseKeyPressEvent(QTimeEdit* self, QKeyEvent* event);
void QTimeEdit_WheelEvent(QTimeEdit* self, QWheelEvent* event);
void QTimeEdit_OnWheelEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseWheelEvent(QTimeEdit* self, QWheelEvent* event);
void QTimeEdit_FocusInEvent(QTimeEdit* self, QFocusEvent* event);
void QTimeEdit_OnFocusInEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseFocusInEvent(QTimeEdit* self, QFocusEvent* event);
bool QTimeEdit_FocusNextPrevChild(QTimeEdit* self, bool next);
void QTimeEdit_OnFocusNextPrevChild(QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseFocusNextPrevChild(QTimeEdit* self, bool next);
int QTimeEdit_Validate(const QTimeEdit* self, libqt_string input, int* pos);
void QTimeEdit_OnValidate(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseValidate(const QTimeEdit* self, libqt_string input, int* pos);
void QTimeEdit_Fixup(const QTimeEdit* self, libqt_string input);
void QTimeEdit_OnFixup(const QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseFixup(const QTimeEdit* self, libqt_string input);
QDateTime* QTimeEdit_DateTimeFromText(const QTimeEdit* self, const libqt_string text);
void QTimeEdit_OnDateTimeFromText(const QTimeEdit* self, intptr_t slot);
QDateTime* QTimeEdit_QBaseDateTimeFromText(const QTimeEdit* self, const libqt_string text);
libqt_string QTimeEdit_TextFromDateTime(const QTimeEdit* self, const QDateTime* dt);
void QTimeEdit_OnTextFromDateTime(const QTimeEdit* self, intptr_t slot);
libqt_string QTimeEdit_QBaseTextFromDateTime(const QTimeEdit* self, const QDateTime* dt);
int QTimeEdit_StepEnabled(const QTimeEdit* self);
void QTimeEdit_OnStepEnabled(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseStepEnabled(const QTimeEdit* self);
void QTimeEdit_MousePressEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_OnMousePressEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseMousePressEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_PaintEvent(QTimeEdit* self, QPaintEvent* event);
void QTimeEdit_OnPaintEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBasePaintEvent(QTimeEdit* self, QPaintEvent* event);
void QTimeEdit_InitStyleOption(const QTimeEdit* self, QStyleOptionSpinBox* option);
void QTimeEdit_OnInitStyleOption(const QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseInitStyleOption(const QTimeEdit* self, QStyleOptionSpinBox* option);
QSize* QTimeEdit_MinimumSizeHint(const QTimeEdit* self);
void QTimeEdit_OnMinimumSizeHint(const QTimeEdit* self, intptr_t slot);
QSize* QTimeEdit_QBaseMinimumSizeHint(const QTimeEdit* self);
QVariant* QTimeEdit_InputMethodQuery(const QTimeEdit* self, int param1);
void QTimeEdit_OnInputMethodQuery(const QTimeEdit* self, intptr_t slot);
QVariant* QTimeEdit_QBaseInputMethodQuery(const QTimeEdit* self, int param1);
void QTimeEdit_ResizeEvent(QTimeEdit* self, QResizeEvent* event);
void QTimeEdit_OnResizeEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseResizeEvent(QTimeEdit* self, QResizeEvent* event);
void QTimeEdit_KeyReleaseEvent(QTimeEdit* self, QKeyEvent* event);
void QTimeEdit_OnKeyReleaseEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseKeyReleaseEvent(QTimeEdit* self, QKeyEvent* event);
void QTimeEdit_FocusOutEvent(QTimeEdit* self, QFocusEvent* event);
void QTimeEdit_OnFocusOutEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseFocusOutEvent(QTimeEdit* self, QFocusEvent* event);
void QTimeEdit_ContextMenuEvent(QTimeEdit* self, QContextMenuEvent* event);
void QTimeEdit_OnContextMenuEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseContextMenuEvent(QTimeEdit* self, QContextMenuEvent* event);
void QTimeEdit_ChangeEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_OnChangeEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseChangeEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_CloseEvent(QTimeEdit* self, QCloseEvent* event);
void QTimeEdit_OnCloseEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseCloseEvent(QTimeEdit* self, QCloseEvent* event);
void QTimeEdit_HideEvent(QTimeEdit* self, QHideEvent* event);
void QTimeEdit_OnHideEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseHideEvent(QTimeEdit* self, QHideEvent* event);
void QTimeEdit_MouseReleaseEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_OnMouseReleaseEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseMouseReleaseEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_MouseMoveEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_OnMouseMoveEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseMouseMoveEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_TimerEvent(QTimeEdit* self, QTimerEvent* event);
void QTimeEdit_OnTimerEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseTimerEvent(QTimeEdit* self, QTimerEvent* event);
void QTimeEdit_ShowEvent(QTimeEdit* self, QShowEvent* event);
void QTimeEdit_OnShowEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseShowEvent(QTimeEdit* self, QShowEvent* event);
int QTimeEdit_DevType(const QTimeEdit* self);
void QTimeEdit_OnDevType(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseDevType(const QTimeEdit* self);
void QTimeEdit_SetVisible(QTimeEdit* self, bool visible);
void QTimeEdit_OnSetVisible(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseSetVisible(QTimeEdit* self, bool visible);
int QTimeEdit_HeightForWidth(const QTimeEdit* self, int param1);
void QTimeEdit_OnHeightForWidth(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseHeightForWidth(const QTimeEdit* self, int param1);
bool QTimeEdit_HasHeightForWidth(const QTimeEdit* self);
void QTimeEdit_OnHasHeightForWidth(const QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseHasHeightForWidth(const QTimeEdit* self);
QPaintEngine* QTimeEdit_PaintEngine(const QTimeEdit* self);
void QTimeEdit_OnPaintEngine(const QTimeEdit* self, intptr_t slot);
QPaintEngine* QTimeEdit_QBasePaintEngine(const QTimeEdit* self);
void QTimeEdit_MouseDoubleClickEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_OnMouseDoubleClickEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseMouseDoubleClickEvent(QTimeEdit* self, QMouseEvent* event);
void QTimeEdit_EnterEvent(QTimeEdit* self, QEnterEvent* event);
void QTimeEdit_OnEnterEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseEnterEvent(QTimeEdit* self, QEnterEvent* event);
void QTimeEdit_LeaveEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_OnLeaveEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseLeaveEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_MoveEvent(QTimeEdit* self, QMoveEvent* event);
void QTimeEdit_OnMoveEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseMoveEvent(QTimeEdit* self, QMoveEvent* event);
void QTimeEdit_TabletEvent(QTimeEdit* self, QTabletEvent* event);
void QTimeEdit_OnTabletEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseTabletEvent(QTimeEdit* self, QTabletEvent* event);
void QTimeEdit_ActionEvent(QTimeEdit* self, QActionEvent* event);
void QTimeEdit_OnActionEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseActionEvent(QTimeEdit* self, QActionEvent* event);
void QTimeEdit_DragEnterEvent(QTimeEdit* self, QDragEnterEvent* event);
void QTimeEdit_OnDragEnterEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseDragEnterEvent(QTimeEdit* self, QDragEnterEvent* event);
void QTimeEdit_DragMoveEvent(QTimeEdit* self, QDragMoveEvent* event);
void QTimeEdit_OnDragMoveEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseDragMoveEvent(QTimeEdit* self, QDragMoveEvent* event);
void QTimeEdit_DragLeaveEvent(QTimeEdit* self, QDragLeaveEvent* event);
void QTimeEdit_OnDragLeaveEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseDragLeaveEvent(QTimeEdit* self, QDragLeaveEvent* event);
void QTimeEdit_DropEvent(QTimeEdit* self, QDropEvent* event);
void QTimeEdit_OnDropEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseDropEvent(QTimeEdit* self, QDropEvent* event);
bool QTimeEdit_NativeEvent(QTimeEdit* self, const libqt_string eventType, void* message, intptr_t* result);
void QTimeEdit_OnNativeEvent(QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseNativeEvent(QTimeEdit* self, const libqt_string eventType, void* message, intptr_t* result);
int QTimeEdit_Metric(const QTimeEdit* self, int param1);
void QTimeEdit_OnMetric(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseMetric(const QTimeEdit* self, int param1);
void QTimeEdit_InitPainter(const QTimeEdit* self, QPainter* painter);
void QTimeEdit_OnInitPainter(const QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseInitPainter(const QTimeEdit* self, QPainter* painter);
QPaintDevice* QTimeEdit_Redirected(const QTimeEdit* self, QPoint* offset);
void QTimeEdit_OnRedirected(const QTimeEdit* self, intptr_t slot);
QPaintDevice* QTimeEdit_QBaseRedirected(const QTimeEdit* self, QPoint* offset);
QPainter* QTimeEdit_SharedPainter(const QTimeEdit* self);
void QTimeEdit_OnSharedPainter(const QTimeEdit* self, intptr_t slot);
QPainter* QTimeEdit_QBaseSharedPainter(const QTimeEdit* self);
void QTimeEdit_InputMethodEvent(QTimeEdit* self, QInputMethodEvent* param1);
void QTimeEdit_OnInputMethodEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseInputMethodEvent(QTimeEdit* self, QInputMethodEvent* param1);
bool QTimeEdit_EventFilter(QTimeEdit* self, QObject* watched, QEvent* event);
void QTimeEdit_OnEventFilter(QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseEventFilter(QTimeEdit* self, QObject* watched, QEvent* event);
void QTimeEdit_ChildEvent(QTimeEdit* self, QChildEvent* event);
void QTimeEdit_OnChildEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseChildEvent(QTimeEdit* self, QChildEvent* event);
void QTimeEdit_CustomEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_OnCustomEvent(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseCustomEvent(QTimeEdit* self, QEvent* event);
void QTimeEdit_ConnectNotify(QTimeEdit* self, const QMetaMethod* signal);
void QTimeEdit_OnConnectNotify(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseConnectNotify(QTimeEdit* self, const QMetaMethod* signal);
void QTimeEdit_DisconnectNotify(QTimeEdit* self, const QMetaMethod* signal);
void QTimeEdit_OnDisconnectNotify(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseDisconnectNotify(QTimeEdit* self, const QMetaMethod* signal);
QLineEdit* QTimeEdit_LineEdit(const QTimeEdit* self);
void QTimeEdit_OnLineEdit(const QTimeEdit* self, intptr_t slot);
QLineEdit* QTimeEdit_QBaseLineEdit(const QTimeEdit* self);
void QTimeEdit_SetLineEdit(QTimeEdit* self, QLineEdit* edit);
void QTimeEdit_OnSetLineEdit(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseSetLineEdit(QTimeEdit* self, QLineEdit* edit);
void QTimeEdit_UpdateMicroFocus(QTimeEdit* self);
void QTimeEdit_OnUpdateMicroFocus(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseUpdateMicroFocus(QTimeEdit* self);
void QTimeEdit_Create(QTimeEdit* self);
void QTimeEdit_OnCreate(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseCreate(QTimeEdit* self);
void QTimeEdit_Destroy(QTimeEdit* self);
void QTimeEdit_OnDestroy(QTimeEdit* self, intptr_t slot);
void QTimeEdit_QBaseDestroy(QTimeEdit* self);
bool QTimeEdit_FocusNextChild(QTimeEdit* self);
void QTimeEdit_OnFocusNextChild(QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseFocusNextChild(QTimeEdit* self);
bool QTimeEdit_FocusPreviousChild(QTimeEdit* self);
void QTimeEdit_OnFocusPreviousChild(QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseFocusPreviousChild(QTimeEdit* self);
QObject* QTimeEdit_Sender(const QTimeEdit* self);
void QTimeEdit_OnSender(const QTimeEdit* self, intptr_t slot);
QObject* QTimeEdit_QBaseSender(const QTimeEdit* self);
int QTimeEdit_SenderSignalIndex(const QTimeEdit* self);
void QTimeEdit_OnSenderSignalIndex(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseSenderSignalIndex(const QTimeEdit* self);
int QTimeEdit_Receivers(const QTimeEdit* self, const char* signal);
void QTimeEdit_OnReceivers(const QTimeEdit* self, intptr_t slot);
int QTimeEdit_QBaseReceivers(const QTimeEdit* self, const char* signal);
bool QTimeEdit_IsSignalConnected(const QTimeEdit* self, const QMetaMethod* signal);
void QTimeEdit_OnIsSignalConnected(const QTimeEdit* self, intptr_t slot);
bool QTimeEdit_QBaseIsSignalConnected(const QTimeEdit* self, const QMetaMethod* signal);
double QTimeEdit_GetDecodedMetricF(const QTimeEdit* self, int metricA, int metricB);
void QTimeEdit_OnGetDecodedMetricF(const QTimeEdit* self, intptr_t slot);
double QTimeEdit_QBaseGetDecodedMetricF(const QTimeEdit* self, int metricA, int metricB);
void QTimeEdit_Delete(QTimeEdit* self);

QDateEdit* QDateEdit_new(QWidget* parent);
QDateEdit* QDateEdit_new2();
QDateEdit* QDateEdit_new3(QDate* date);
QDateEdit* QDateEdit_new4(QDate* date, QWidget* parent);
QMetaObject* QDateEdit_MetaObject(const QDateEdit* self);
void* QDateEdit_Metacast(QDateEdit* self, const char* param1);
int QDateEdit_Metacall(QDateEdit* self, int param1, int param2, void** param3);
libqt_string QDateEdit_Tr(const char* s);
void QDateEdit_UserDateChanged(QDateEdit* self, QDate* date);
void QDateEdit_Connect_UserDateChanged(QDateEdit* self, intptr_t slot);
libqt_string QDateEdit_Tr2(const char* s, const char* c);
libqt_string QDateEdit_Tr3(const char* s, const char* c, int n);
void QDateEdit_OnMetacall(QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseMetacall(QDateEdit* self, int param1, int param2, void** param3);
QSize* QDateEdit_SizeHint(const QDateEdit* self);
void QDateEdit_OnSizeHint(const QDateEdit* self, intptr_t slot);
QSize* QDateEdit_QBaseSizeHint(const QDateEdit* self);
void QDateEdit_Clear(QDateEdit* self);
void QDateEdit_OnClear(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseClear(QDateEdit* self);
void QDateEdit_StepBy(QDateEdit* self, int steps);
void QDateEdit_OnStepBy(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseStepBy(QDateEdit* self, int steps);
bool QDateEdit_Event(QDateEdit* self, QEvent* event);
void QDateEdit_OnEvent(QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseEvent(QDateEdit* self, QEvent* event);
void QDateEdit_KeyPressEvent(QDateEdit* self, QKeyEvent* event);
void QDateEdit_OnKeyPressEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseKeyPressEvent(QDateEdit* self, QKeyEvent* event);
void QDateEdit_WheelEvent(QDateEdit* self, QWheelEvent* event);
void QDateEdit_OnWheelEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseWheelEvent(QDateEdit* self, QWheelEvent* event);
void QDateEdit_FocusInEvent(QDateEdit* self, QFocusEvent* event);
void QDateEdit_OnFocusInEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseFocusInEvent(QDateEdit* self, QFocusEvent* event);
bool QDateEdit_FocusNextPrevChild(QDateEdit* self, bool next);
void QDateEdit_OnFocusNextPrevChild(QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseFocusNextPrevChild(QDateEdit* self, bool next);
int QDateEdit_Validate(const QDateEdit* self, libqt_string input, int* pos);
void QDateEdit_OnValidate(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseValidate(const QDateEdit* self, libqt_string input, int* pos);
void QDateEdit_Fixup(const QDateEdit* self, libqt_string input);
void QDateEdit_OnFixup(const QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseFixup(const QDateEdit* self, libqt_string input);
QDateTime* QDateEdit_DateTimeFromText(const QDateEdit* self, const libqt_string text);
void QDateEdit_OnDateTimeFromText(const QDateEdit* self, intptr_t slot);
QDateTime* QDateEdit_QBaseDateTimeFromText(const QDateEdit* self, const libqt_string text);
libqt_string QDateEdit_TextFromDateTime(const QDateEdit* self, const QDateTime* dt);
void QDateEdit_OnTextFromDateTime(const QDateEdit* self, intptr_t slot);
libqt_string QDateEdit_QBaseTextFromDateTime(const QDateEdit* self, const QDateTime* dt);
int QDateEdit_StepEnabled(const QDateEdit* self);
void QDateEdit_OnStepEnabled(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseStepEnabled(const QDateEdit* self);
void QDateEdit_MousePressEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_OnMousePressEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseMousePressEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_PaintEvent(QDateEdit* self, QPaintEvent* event);
void QDateEdit_OnPaintEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBasePaintEvent(QDateEdit* self, QPaintEvent* event);
void QDateEdit_InitStyleOption(const QDateEdit* self, QStyleOptionSpinBox* option);
void QDateEdit_OnInitStyleOption(const QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseInitStyleOption(const QDateEdit* self, QStyleOptionSpinBox* option);
QSize* QDateEdit_MinimumSizeHint(const QDateEdit* self);
void QDateEdit_OnMinimumSizeHint(const QDateEdit* self, intptr_t slot);
QSize* QDateEdit_QBaseMinimumSizeHint(const QDateEdit* self);
QVariant* QDateEdit_InputMethodQuery(const QDateEdit* self, int param1);
void QDateEdit_OnInputMethodQuery(const QDateEdit* self, intptr_t slot);
QVariant* QDateEdit_QBaseInputMethodQuery(const QDateEdit* self, int param1);
void QDateEdit_ResizeEvent(QDateEdit* self, QResizeEvent* event);
void QDateEdit_OnResizeEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseResizeEvent(QDateEdit* self, QResizeEvent* event);
void QDateEdit_KeyReleaseEvent(QDateEdit* self, QKeyEvent* event);
void QDateEdit_OnKeyReleaseEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseKeyReleaseEvent(QDateEdit* self, QKeyEvent* event);
void QDateEdit_FocusOutEvent(QDateEdit* self, QFocusEvent* event);
void QDateEdit_OnFocusOutEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseFocusOutEvent(QDateEdit* self, QFocusEvent* event);
void QDateEdit_ContextMenuEvent(QDateEdit* self, QContextMenuEvent* event);
void QDateEdit_OnContextMenuEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseContextMenuEvent(QDateEdit* self, QContextMenuEvent* event);
void QDateEdit_ChangeEvent(QDateEdit* self, QEvent* event);
void QDateEdit_OnChangeEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseChangeEvent(QDateEdit* self, QEvent* event);
void QDateEdit_CloseEvent(QDateEdit* self, QCloseEvent* event);
void QDateEdit_OnCloseEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseCloseEvent(QDateEdit* self, QCloseEvent* event);
void QDateEdit_HideEvent(QDateEdit* self, QHideEvent* event);
void QDateEdit_OnHideEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseHideEvent(QDateEdit* self, QHideEvent* event);
void QDateEdit_MouseReleaseEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_OnMouseReleaseEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseMouseReleaseEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_MouseMoveEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_OnMouseMoveEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseMouseMoveEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_TimerEvent(QDateEdit* self, QTimerEvent* event);
void QDateEdit_OnTimerEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseTimerEvent(QDateEdit* self, QTimerEvent* event);
void QDateEdit_ShowEvent(QDateEdit* self, QShowEvent* event);
void QDateEdit_OnShowEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseShowEvent(QDateEdit* self, QShowEvent* event);
int QDateEdit_DevType(const QDateEdit* self);
void QDateEdit_OnDevType(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseDevType(const QDateEdit* self);
void QDateEdit_SetVisible(QDateEdit* self, bool visible);
void QDateEdit_OnSetVisible(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseSetVisible(QDateEdit* self, bool visible);
int QDateEdit_HeightForWidth(const QDateEdit* self, int param1);
void QDateEdit_OnHeightForWidth(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseHeightForWidth(const QDateEdit* self, int param1);
bool QDateEdit_HasHeightForWidth(const QDateEdit* self);
void QDateEdit_OnHasHeightForWidth(const QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseHasHeightForWidth(const QDateEdit* self);
QPaintEngine* QDateEdit_PaintEngine(const QDateEdit* self);
void QDateEdit_OnPaintEngine(const QDateEdit* self, intptr_t slot);
QPaintEngine* QDateEdit_QBasePaintEngine(const QDateEdit* self);
void QDateEdit_MouseDoubleClickEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_OnMouseDoubleClickEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseMouseDoubleClickEvent(QDateEdit* self, QMouseEvent* event);
void QDateEdit_EnterEvent(QDateEdit* self, QEnterEvent* event);
void QDateEdit_OnEnterEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseEnterEvent(QDateEdit* self, QEnterEvent* event);
void QDateEdit_LeaveEvent(QDateEdit* self, QEvent* event);
void QDateEdit_OnLeaveEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseLeaveEvent(QDateEdit* self, QEvent* event);
void QDateEdit_MoveEvent(QDateEdit* self, QMoveEvent* event);
void QDateEdit_OnMoveEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseMoveEvent(QDateEdit* self, QMoveEvent* event);
void QDateEdit_TabletEvent(QDateEdit* self, QTabletEvent* event);
void QDateEdit_OnTabletEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseTabletEvent(QDateEdit* self, QTabletEvent* event);
void QDateEdit_ActionEvent(QDateEdit* self, QActionEvent* event);
void QDateEdit_OnActionEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseActionEvent(QDateEdit* self, QActionEvent* event);
void QDateEdit_DragEnterEvent(QDateEdit* self, QDragEnterEvent* event);
void QDateEdit_OnDragEnterEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseDragEnterEvent(QDateEdit* self, QDragEnterEvent* event);
void QDateEdit_DragMoveEvent(QDateEdit* self, QDragMoveEvent* event);
void QDateEdit_OnDragMoveEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseDragMoveEvent(QDateEdit* self, QDragMoveEvent* event);
void QDateEdit_DragLeaveEvent(QDateEdit* self, QDragLeaveEvent* event);
void QDateEdit_OnDragLeaveEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseDragLeaveEvent(QDateEdit* self, QDragLeaveEvent* event);
void QDateEdit_DropEvent(QDateEdit* self, QDropEvent* event);
void QDateEdit_OnDropEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseDropEvent(QDateEdit* self, QDropEvent* event);
bool QDateEdit_NativeEvent(QDateEdit* self, const libqt_string eventType, void* message, intptr_t* result);
void QDateEdit_OnNativeEvent(QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseNativeEvent(QDateEdit* self, const libqt_string eventType, void* message, intptr_t* result);
int QDateEdit_Metric(const QDateEdit* self, int param1);
void QDateEdit_OnMetric(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseMetric(const QDateEdit* self, int param1);
void QDateEdit_InitPainter(const QDateEdit* self, QPainter* painter);
void QDateEdit_OnInitPainter(const QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseInitPainter(const QDateEdit* self, QPainter* painter);
QPaintDevice* QDateEdit_Redirected(const QDateEdit* self, QPoint* offset);
void QDateEdit_OnRedirected(const QDateEdit* self, intptr_t slot);
QPaintDevice* QDateEdit_QBaseRedirected(const QDateEdit* self, QPoint* offset);
QPainter* QDateEdit_SharedPainter(const QDateEdit* self);
void QDateEdit_OnSharedPainter(const QDateEdit* self, intptr_t slot);
QPainter* QDateEdit_QBaseSharedPainter(const QDateEdit* self);
void QDateEdit_InputMethodEvent(QDateEdit* self, QInputMethodEvent* param1);
void QDateEdit_OnInputMethodEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseInputMethodEvent(QDateEdit* self, QInputMethodEvent* param1);
bool QDateEdit_EventFilter(QDateEdit* self, QObject* watched, QEvent* event);
void QDateEdit_OnEventFilter(QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseEventFilter(QDateEdit* self, QObject* watched, QEvent* event);
void QDateEdit_ChildEvent(QDateEdit* self, QChildEvent* event);
void QDateEdit_OnChildEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseChildEvent(QDateEdit* self, QChildEvent* event);
void QDateEdit_CustomEvent(QDateEdit* self, QEvent* event);
void QDateEdit_OnCustomEvent(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseCustomEvent(QDateEdit* self, QEvent* event);
void QDateEdit_ConnectNotify(QDateEdit* self, const QMetaMethod* signal);
void QDateEdit_OnConnectNotify(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseConnectNotify(QDateEdit* self, const QMetaMethod* signal);
void QDateEdit_DisconnectNotify(QDateEdit* self, const QMetaMethod* signal);
void QDateEdit_OnDisconnectNotify(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseDisconnectNotify(QDateEdit* self, const QMetaMethod* signal);
QLineEdit* QDateEdit_LineEdit(const QDateEdit* self);
void QDateEdit_OnLineEdit(const QDateEdit* self, intptr_t slot);
QLineEdit* QDateEdit_QBaseLineEdit(const QDateEdit* self);
void QDateEdit_SetLineEdit(QDateEdit* self, QLineEdit* edit);
void QDateEdit_OnSetLineEdit(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseSetLineEdit(QDateEdit* self, QLineEdit* edit);
void QDateEdit_UpdateMicroFocus(QDateEdit* self);
void QDateEdit_OnUpdateMicroFocus(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseUpdateMicroFocus(QDateEdit* self);
void QDateEdit_Create(QDateEdit* self);
void QDateEdit_OnCreate(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseCreate(QDateEdit* self);
void QDateEdit_Destroy(QDateEdit* self);
void QDateEdit_OnDestroy(QDateEdit* self, intptr_t slot);
void QDateEdit_QBaseDestroy(QDateEdit* self);
bool QDateEdit_FocusNextChild(QDateEdit* self);
void QDateEdit_OnFocusNextChild(QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseFocusNextChild(QDateEdit* self);
bool QDateEdit_FocusPreviousChild(QDateEdit* self);
void QDateEdit_OnFocusPreviousChild(QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseFocusPreviousChild(QDateEdit* self);
QObject* QDateEdit_Sender(const QDateEdit* self);
void QDateEdit_OnSender(const QDateEdit* self, intptr_t slot);
QObject* QDateEdit_QBaseSender(const QDateEdit* self);
int QDateEdit_SenderSignalIndex(const QDateEdit* self);
void QDateEdit_OnSenderSignalIndex(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseSenderSignalIndex(const QDateEdit* self);
int QDateEdit_Receivers(const QDateEdit* self, const char* signal);
void QDateEdit_OnReceivers(const QDateEdit* self, intptr_t slot);
int QDateEdit_QBaseReceivers(const QDateEdit* self, const char* signal);
bool QDateEdit_IsSignalConnected(const QDateEdit* self, const QMetaMethod* signal);
void QDateEdit_OnIsSignalConnected(const QDateEdit* self, intptr_t slot);
bool QDateEdit_QBaseIsSignalConnected(const QDateEdit* self, const QMetaMethod* signal);
double QDateEdit_GetDecodedMetricF(const QDateEdit* self, int metricA, int metricB);
void QDateEdit_OnGetDecodedMetricF(const QDateEdit* self, intptr_t slot);
double QDateEdit_QBaseGetDecodedMetricF(const QDateEdit* self, int metricA, int metricB);
void QDateEdit_Delete(QDateEdit* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
