#pragma once
#ifndef SRC_OPENGLC_LIBQOPENGLVERSIONFUNCTIONS_H
#define SRC_OPENGLC_LIBQOPENGLVERSIONFUNCTIONS_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_0_CoreBackend__Functions)
typedef QOpenGLFunctions_1_0_CoreBackend::Functions QOpenGLFunctions_1_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_0_DeprecatedBackend::Functions QOpenGLFunctions_1_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_1_CoreBackend__Functions)
typedef QOpenGLFunctions_1_1_CoreBackend::Functions QOpenGLFunctions_1_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_1_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_1_DeprecatedBackend::Functions QOpenGLFunctions_1_1_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_2_CoreBackend__Functions)
typedef QOpenGLFunctions_1_2_CoreBackend::Functions QOpenGLFunctions_1_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_2_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_2_DeprecatedBackend::Functions QOpenGLFunctions_1_2_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_3_CoreBackend__Functions)
typedef QOpenGLFunctions_1_3_CoreBackend::Functions QOpenGLFunctions_1_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_3_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_3_DeprecatedBackend::Functions QOpenGLFunctions_1_3_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_4_CoreBackend__Functions)
typedef QOpenGLFunctions_1_4_CoreBackend::Functions QOpenGLFunctions_1_4_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_4_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_4_DeprecatedBackend::Functions QOpenGLFunctions_1_4_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_5_CoreBackend__Functions)
typedef QOpenGLFunctions_1_5_CoreBackend::Functions QOpenGLFunctions_1_5_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_0_CoreBackend__Functions)
typedef QOpenGLFunctions_2_0_CoreBackend::Functions QOpenGLFunctions_2_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_2_0_DeprecatedBackend::Functions QOpenGLFunctions_2_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_1_CoreBackend__Functions)
typedef QOpenGLFunctions_2_1_CoreBackend::Functions QOpenGLFunctions_2_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_0_CoreBackend__Functions)
typedef QOpenGLFunctions_3_0_CoreBackend::Functions QOpenGLFunctions_3_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_3_0_DeprecatedBackend::Functions QOpenGLFunctions_3_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_1_CoreBackend__Functions)
typedef QOpenGLFunctions_3_1_CoreBackend::Functions QOpenGLFunctions_3_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_2_CoreBackend__Functions)
typedef QOpenGLFunctions_3_2_CoreBackend::Functions QOpenGLFunctions_3_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_3_CoreBackend__Functions)
typedef QOpenGLFunctions_3_3_CoreBackend::Functions QOpenGLFunctions_3_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_3_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_3_3_DeprecatedBackend::Functions QOpenGLFunctions_3_3_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_0_CoreBackend__Functions)
typedef QOpenGLFunctions_4_0_CoreBackend::Functions QOpenGLFunctions_4_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_1_CoreBackend__Functions)
typedef QOpenGLFunctions_4_1_CoreBackend::Functions QOpenGLFunctions_4_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_2_CoreBackend__Functions)
typedef QOpenGLFunctions_4_2_CoreBackend::Functions QOpenGLFunctions_4_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_3_CoreBackend__Functions)
typedef QOpenGLFunctions_4_3_CoreBackend::Functions QOpenGLFunctions_4_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_4_CoreBackend__Functions)
typedef QOpenGLFunctions_4_4_CoreBackend::Functions QOpenGLFunctions_4_4_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_5_CoreBackend__Functions)
typedef QOpenGLFunctions_4_5_CoreBackend::Functions QOpenGLFunctions_4_5_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_5_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_4_5_DeprecatedBackend::Functions QOpenGLFunctions_4_5_DeprecatedBackend__Functions;
#endif
#else
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLContext QOpenGLContext;
typedef struct QOpenGLFunctions_1_0_CoreBackend QOpenGLFunctions_1_0_CoreBackend;
typedef struct QOpenGLFunctions_1_0_CoreBackend__Functions QOpenGLFunctions_1_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_0_DeprecatedBackend QOpenGLFunctions_1_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_0_DeprecatedBackend__Functions QOpenGLFunctions_1_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_1_CoreBackend QOpenGLFunctions_1_1_CoreBackend;
typedef struct QOpenGLFunctions_1_1_CoreBackend__Functions QOpenGLFunctions_1_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_1_DeprecatedBackend QOpenGLFunctions_1_1_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_1_DeprecatedBackend__Functions QOpenGLFunctions_1_1_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_2_CoreBackend QOpenGLFunctions_1_2_CoreBackend;
typedef struct QOpenGLFunctions_1_2_CoreBackend__Functions QOpenGLFunctions_1_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_2_DeprecatedBackend QOpenGLFunctions_1_2_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_2_DeprecatedBackend__Functions QOpenGLFunctions_1_2_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_3_CoreBackend QOpenGLFunctions_1_3_CoreBackend;
typedef struct QOpenGLFunctions_1_3_CoreBackend__Functions QOpenGLFunctions_1_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_3_DeprecatedBackend QOpenGLFunctions_1_3_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_3_DeprecatedBackend__Functions QOpenGLFunctions_1_3_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_4_CoreBackend QOpenGLFunctions_1_4_CoreBackend;
typedef struct QOpenGLFunctions_1_4_CoreBackend__Functions QOpenGLFunctions_1_4_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_4_DeprecatedBackend QOpenGLFunctions_1_4_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_4_DeprecatedBackend__Functions QOpenGLFunctions_1_4_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_5_CoreBackend QOpenGLFunctions_1_5_CoreBackend;
typedef struct QOpenGLFunctions_1_5_CoreBackend__Functions QOpenGLFunctions_1_5_CoreBackend__Functions;
typedef struct QOpenGLFunctions_2_0_CoreBackend QOpenGLFunctions_2_0_CoreBackend;
typedef struct QOpenGLFunctions_2_0_CoreBackend__Functions QOpenGLFunctions_2_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_2_0_DeprecatedBackend QOpenGLFunctions_2_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_2_0_DeprecatedBackend__Functions QOpenGLFunctions_2_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_2_1_CoreBackend QOpenGLFunctions_2_1_CoreBackend;
typedef struct QOpenGLFunctions_2_1_CoreBackend__Functions QOpenGLFunctions_2_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_0_CoreBackend QOpenGLFunctions_3_0_CoreBackend;
typedef struct QOpenGLFunctions_3_0_CoreBackend__Functions QOpenGLFunctions_3_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_0_DeprecatedBackend QOpenGLFunctions_3_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_3_0_DeprecatedBackend__Functions QOpenGLFunctions_3_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_3_1_CoreBackend QOpenGLFunctions_3_1_CoreBackend;
typedef struct QOpenGLFunctions_3_1_CoreBackend__Functions QOpenGLFunctions_3_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_2_CoreBackend QOpenGLFunctions_3_2_CoreBackend;
typedef struct QOpenGLFunctions_3_2_CoreBackend__Functions QOpenGLFunctions_3_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_3_CoreBackend QOpenGLFunctions_3_3_CoreBackend;
typedef struct QOpenGLFunctions_3_3_CoreBackend__Functions QOpenGLFunctions_3_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_3_DeprecatedBackend QOpenGLFunctions_3_3_DeprecatedBackend;
typedef struct QOpenGLFunctions_3_3_DeprecatedBackend__Functions QOpenGLFunctions_3_3_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_4_0_CoreBackend QOpenGLFunctions_4_0_CoreBackend;
typedef struct QOpenGLFunctions_4_0_CoreBackend__Functions QOpenGLFunctions_4_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_1_CoreBackend QOpenGLFunctions_4_1_CoreBackend;
typedef struct QOpenGLFunctions_4_1_CoreBackend__Functions QOpenGLFunctions_4_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_2_CoreBackend QOpenGLFunctions_4_2_CoreBackend;
typedef struct QOpenGLFunctions_4_2_CoreBackend__Functions QOpenGLFunctions_4_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_3_CoreBackend QOpenGLFunctions_4_3_CoreBackend;
typedef struct QOpenGLFunctions_4_3_CoreBackend__Functions QOpenGLFunctions_4_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_4_CoreBackend QOpenGLFunctions_4_4_CoreBackend;
typedef struct QOpenGLFunctions_4_4_CoreBackend__Functions QOpenGLFunctions_4_4_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_5_CoreBackend QOpenGLFunctions_4_5_CoreBackend;
typedef struct QOpenGLFunctions_4_5_CoreBackend__Functions QOpenGLFunctions_4_5_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_5_DeprecatedBackend QOpenGLFunctions_4_5_DeprecatedBackend;
typedef struct QOpenGLFunctions_4_5_DeprecatedBackend__Functions QOpenGLFunctions_4_5_DeprecatedBackend__Functions;
typedef struct QOpenGLVersionFunctionsBackend QOpenGLVersionFunctionsBackend;
typedef struct QOpenGLVersionFunctionsStorage QOpenGLVersionFunctionsStorage;
typedef struct QOpenGLVersionStatus QOpenGLVersionStatus;
#endif

QOpenGLVersionStatus* QOpenGLVersionStatus_new(const QOpenGLVersionStatus* other);
QOpenGLVersionStatus* QOpenGLVersionStatus_new2(QOpenGLVersionStatus* other);
QOpenGLVersionStatus* QOpenGLVersionStatus_new3();
QOpenGLVersionStatus* QOpenGLVersionStatus_new4(int majorVersion, int minorVersion, int functionStatus);
QOpenGLVersionStatus* QOpenGLVersionStatus_new5(const QOpenGLVersionStatus* param1);
libqt_pair /* tuple of int and int */ QOpenGLVersionStatus_Version(const QOpenGLVersionStatus* self);
void QOpenGLVersionStatus_SetVersion(QOpenGLVersionStatus* self, libqt_pair /* tuple of int and int */ version);
int QOpenGLVersionStatus_Status(const QOpenGLVersionStatus* self);
void QOpenGLVersionStatus_SetStatus(QOpenGLVersionStatus* self, int status);
void QOpenGLVersionStatus_OperatorAssign(QOpenGLVersionStatus* self, const QOpenGLVersionStatus* param1);
void QOpenGLVersionStatus_Delete(QOpenGLVersionStatus* self);

QOpenGLContext* QOpenGLVersionFunctionsBackend_Context(const QOpenGLVersionFunctionsBackend* self);
void QOpenGLVersionFunctionsBackend_SetContext(QOpenGLVersionFunctionsBackend* self, QOpenGLContext* context);
void QOpenGLVersionFunctionsBackend_Delete(QOpenGLVersionFunctionsBackend* self);

bool QAbstractOpenGLFunctions_InitializeOpenGLFunctions(QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_Delete(QAbstractOpenGLFunctions* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
