#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_QSCINTILLAC_LIBQSCISCINTILLABASE_H
#define SRC_RESTRICTED_EXTRAS_QSCINTILLAC_LIBQSCISCINTILLABASE_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QColor QColor;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QResizeEvent QResizeEvent;
typedef struct QScrollBar QScrollBar;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QsciScintillaBase QsciScintillaBase;
#endif

QsciScintillaBase* QsciScintillaBase_new(QWidget* parent);
QsciScintillaBase* QsciScintillaBase_new2();
QMetaObject* QsciScintillaBase_MetaObject(const QsciScintillaBase* self);
void* QsciScintillaBase_Metacast(QsciScintillaBase* self, const char* param1);
int QsciScintillaBase_Metacall(QsciScintillaBase* self, int param1, int param2, void** param3);
libqt_string QsciScintillaBase_Tr(const char* s);
QsciScintillaBase* QsciScintillaBase_Pool();
void QsciScintillaBase_ReplaceHorizontalScrollBar(QsciScintillaBase* self, QScrollBar* scrollBar);
void QsciScintillaBase_ReplaceVerticalScrollBar(QsciScintillaBase* self, QScrollBar* scrollBar);
long QsciScintillaBase_SendScintilla(const QsciScintillaBase* self, unsigned int msg);
long QsciScintillaBase_SendScintilla2(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, void* lParam);
long QsciScintillaBase_SendScintilla3(const QsciScintillaBase* self, unsigned int msg, uintptr_t wParam, const char* lParam);
long QsciScintillaBase_SendScintilla4(const QsciScintillaBase* self, unsigned int msg, const char* lParam);
long QsciScintillaBase_SendScintilla5(const QsciScintillaBase* self, unsigned int msg, const char* wParam, const char* lParam);
long QsciScintillaBase_SendScintilla6(const QsciScintillaBase* self, unsigned int msg, long wParam);
long QsciScintillaBase_SendScintilla7(const QsciScintillaBase* self, unsigned int msg, int wParam);
long QsciScintillaBase_SendScintilla8(const QsciScintillaBase* self, unsigned int msg, long cpMin, long cpMax, char* lpstrText);
long QsciScintillaBase_SendScintilla9(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, const QColor* col);
long QsciScintillaBase_SendScintilla10(const QsciScintillaBase* self, unsigned int msg, const QColor* col);
long QsciScintillaBase_SendScintilla11(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, QPainter* hdc, const QRect* rc, long cpMin, long cpMax);
long QsciScintillaBase_SendScintilla12(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, const QPixmap* lParam);
long QsciScintillaBase_SendScintilla13(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, const QImage* lParam);
void* QsciScintillaBase_SendScintillaPtrResult(const QsciScintillaBase* self, unsigned int msg);
int QsciScintillaBase_CommandKey(int qt_key, int* modifiers);
void QsciScintillaBase_QSCN_SELCHANGED(QsciScintillaBase* self, bool yes);
void QsciScintillaBase_SCN_AUTOCCANCELLED(QsciScintillaBase* self);
void QsciScintillaBase_SCN_AUTOCCHARDELETED(QsciScintillaBase* self);
void QsciScintillaBase_SCN_AUTOCCOMPLETED(QsciScintillaBase* self, const char* selection, int position, int ch, int method);
void QsciScintillaBase_SCN_AUTOCSELECTION(QsciScintillaBase* self, const char* selection, int position, int ch, int method);
void QsciScintillaBase_SCN_AUTOCSELECTION2(QsciScintillaBase* self, const char* selection, int position);
void QsciScintillaBase_SCN_AUTOCSELECTIONCHANGE(QsciScintillaBase* self, const char* selection, int id, int position);
void QsciScintillaBase_SCEN_CHANGE(QsciScintillaBase* self);
void QsciScintillaBase_SCN_CALLTIPCLICK(QsciScintillaBase* self, int direction);
void QsciScintillaBase_SCN_CHARADDED(QsciScintillaBase* self, int charadded);
void QsciScintillaBase_SCN_DOUBLECLICK(QsciScintillaBase* self, int position, int line, int modifiers);
void QsciScintillaBase_SCN_DWELLEND(QsciScintillaBase* self, int position, int x, int y);
void QsciScintillaBase_SCN_DWELLSTART(QsciScintillaBase* self, int position, int x, int y);
void QsciScintillaBase_SCN_FOCUSIN(QsciScintillaBase* self);
void QsciScintillaBase_SCN_FOCUSOUT(QsciScintillaBase* self);
void QsciScintillaBase_SCN_HOTSPOTCLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_SCN_HOTSPOTDOUBLECLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_SCN_HOTSPOTRELEASECLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_SCN_INDICATORCLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_SCN_INDICATORRELEASE(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_SCN_MACRORECORD(QsciScintillaBase* self, unsigned int param1, unsigned long param2, void* param3);
void QsciScintillaBase_SCN_MARGINCLICK(QsciScintillaBase* self, int position, int modifiers, int margin);
void QsciScintillaBase_SCN_MARGINRIGHTCLICK(QsciScintillaBase* self, int position, int modifiers, int margin);
void QsciScintillaBase_SCN_MODIFIED(QsciScintillaBase* self, int param1, int param2, const char* param3, int param4, int param5, int param6, int param7, int param8, int param9, int param10);
void QsciScintillaBase_SCN_MODIFYATTEMPTRO(QsciScintillaBase* self);
void QsciScintillaBase_SCN_NEEDSHOWN(QsciScintillaBase* self, int param1, int param2);
void QsciScintillaBase_SCN_PAINTED(QsciScintillaBase* self);
void QsciScintillaBase_SCN_SAVEPOINTLEFT(QsciScintillaBase* self);
void QsciScintillaBase_SCN_SAVEPOINTREACHED(QsciScintillaBase* self);
void QsciScintillaBase_SCN_STYLENEEDED(QsciScintillaBase* self, int position);
void QsciScintillaBase_SCN_URIDROPPED(QsciScintillaBase* self, const QUrl* url);
void QsciScintillaBase_SCN_UPDATEUI(QsciScintillaBase* self, int updated);
void QsciScintillaBase_SCN_USERLISTSELECTION(QsciScintillaBase* self, const char* selection, int id, int ch, int method, int position);
void QsciScintillaBase_SCN_USERLISTSELECTION2(QsciScintillaBase* self, const char* selection, int id, int ch, int method);
void QsciScintillaBase_SCN_USERLISTSELECTION3(QsciScintillaBase* self, const char* selection, int id);
void QsciScintillaBase_SCN_ZOOM(QsciScintillaBase* self);
bool QsciScintillaBase_CanInsertFromMimeData(const QsciScintillaBase* self, const QMimeData* source);
libqt_string QsciScintillaBase_FromMimeData(const QsciScintillaBase* self, const QMimeData* source, bool* rectangular);
QMimeData* QsciScintillaBase_ToMimeData(const QsciScintillaBase* self, const libqt_string text, bool rectangular);
void QsciScintillaBase_ChangeEvent(QsciScintillaBase* self, QEvent* e);
void QsciScintillaBase_ContextMenuEvent(QsciScintillaBase* self, QContextMenuEvent* e);
void QsciScintillaBase_DragEnterEvent(QsciScintillaBase* self, QDragEnterEvent* e);
void QsciScintillaBase_DragLeaveEvent(QsciScintillaBase* self, QDragLeaveEvent* e);
void QsciScintillaBase_DragMoveEvent(QsciScintillaBase* self, QDragMoveEvent* e);
void QsciScintillaBase_DropEvent(QsciScintillaBase* self, QDropEvent* e);
void QsciScintillaBase_FocusInEvent(QsciScintillaBase* self, QFocusEvent* e);
void QsciScintillaBase_FocusOutEvent(QsciScintillaBase* self, QFocusEvent* e);
bool QsciScintillaBase_FocusNextPrevChild(QsciScintillaBase* self, bool next);
void QsciScintillaBase_KeyPressEvent(QsciScintillaBase* self, QKeyEvent* e);
void QsciScintillaBase_InputMethodEvent(QsciScintillaBase* self, QInputMethodEvent* event);
void QsciScintillaBase_MouseDoubleClickEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_MouseMoveEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_MousePressEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_MouseReleaseEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_PaintEvent(QsciScintillaBase* self, QPaintEvent* e);
void QsciScintillaBase_ResizeEvent(QsciScintillaBase* self, QResizeEvent* e);
void QsciScintillaBase_ScrollContentsBy(QsciScintillaBase* self, int dx, int dy);
libqt_string QsciScintillaBase_Tr2(const char* s, const char* c);
libqt_string QsciScintillaBase_Tr3(const char* s, const char* c, int n);
long QsciScintillaBase_SendScintilla22(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam);
long QsciScintillaBase_SendScintilla32(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, long lParam);
void QsciScintillaBase_OnMetacall(QsciScintillaBase* self, intptr_t slot);
int QsciScintillaBase_QBaseMetacall(QsciScintillaBase* self, int param1, int param2, void** param3);
void QsciScintillaBase_OnCanInsertFromMimeData(const QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseCanInsertFromMimeData(const QsciScintillaBase* self, const QMimeData* source);
void QsciScintillaBase_OnFromMimeData(const QsciScintillaBase* self, intptr_t slot);
libqt_string QsciScintillaBase_QBaseFromMimeData(const QsciScintillaBase* self, const QMimeData* source, bool* rectangular);
void QsciScintillaBase_OnToMimeData(const QsciScintillaBase* self, intptr_t slot);
QMimeData* QsciScintillaBase_QBaseToMimeData(const QsciScintillaBase* self, const libqt_string text, bool rectangular);
void QsciScintillaBase_OnChangeEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseChangeEvent(QsciScintillaBase* self, QEvent* e);
void QsciScintillaBase_OnContextMenuEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseContextMenuEvent(QsciScintillaBase* self, QContextMenuEvent* e);
void QsciScintillaBase_OnDragEnterEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDragEnterEvent(QsciScintillaBase* self, QDragEnterEvent* e);
void QsciScintillaBase_OnDragLeaveEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDragLeaveEvent(QsciScintillaBase* self, QDragLeaveEvent* e);
void QsciScintillaBase_OnDragMoveEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDragMoveEvent(QsciScintillaBase* self, QDragMoveEvent* e);
void QsciScintillaBase_OnDropEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDropEvent(QsciScintillaBase* self, QDropEvent* e);
void QsciScintillaBase_OnFocusInEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseFocusInEvent(QsciScintillaBase* self, QFocusEvent* e);
void QsciScintillaBase_OnFocusOutEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseFocusOutEvent(QsciScintillaBase* self, QFocusEvent* e);
void QsciScintillaBase_OnFocusNextPrevChild(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseFocusNextPrevChild(QsciScintillaBase* self, bool next);
void QsciScintillaBase_OnKeyPressEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseKeyPressEvent(QsciScintillaBase* self, QKeyEvent* e);
void QsciScintillaBase_OnInputMethodEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseInputMethodEvent(QsciScintillaBase* self, QInputMethodEvent* event);
void QsciScintillaBase_OnMouseDoubleClickEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseMouseDoubleClickEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_OnMouseMoveEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseMouseMoveEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_OnMousePressEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseMousePressEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_OnMouseReleaseEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseMouseReleaseEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_OnPaintEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBasePaintEvent(QsciScintillaBase* self, QPaintEvent* e);
void QsciScintillaBase_OnResizeEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseResizeEvent(QsciScintillaBase* self, QResizeEvent* e);
void QsciScintillaBase_OnScrollContentsBy(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseScrollContentsBy(QsciScintillaBase* self, int dx, int dy);
QSize* QsciScintillaBase_MinimumSizeHint(const QsciScintillaBase* self);
void QsciScintillaBase_OnMinimumSizeHint(const QsciScintillaBase* self, intptr_t slot);
QSize* QsciScintillaBase_QBaseMinimumSizeHint(const QsciScintillaBase* self);
QSize* QsciScintillaBase_SizeHint(const QsciScintillaBase* self);
void QsciScintillaBase_OnSizeHint(const QsciScintillaBase* self, intptr_t slot);
QSize* QsciScintillaBase_QBaseSizeHint(const QsciScintillaBase* self);
void QsciScintillaBase_SetupViewport(QsciScintillaBase* self, QWidget* viewport);
void QsciScintillaBase_OnSetupViewport(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseSetupViewport(QsciScintillaBase* self, QWidget* viewport);
bool QsciScintillaBase_EventFilter(QsciScintillaBase* self, QObject* param1, QEvent* param2);
void QsciScintillaBase_OnEventFilter(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseEventFilter(QsciScintillaBase* self, QObject* param1, QEvent* param2);
bool QsciScintillaBase_Event(QsciScintillaBase* self, QEvent* param1);
void QsciScintillaBase_OnEvent(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseEvent(QsciScintillaBase* self, QEvent* param1);
bool QsciScintillaBase_ViewportEvent(QsciScintillaBase* self, QEvent* param1);
void QsciScintillaBase_OnViewportEvent(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseViewportEvent(QsciScintillaBase* self, QEvent* param1);
void QsciScintillaBase_WheelEvent(QsciScintillaBase* self, QWheelEvent* param1);
void QsciScintillaBase_OnWheelEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseWheelEvent(QsciScintillaBase* self, QWheelEvent* param1);
QSize* QsciScintillaBase_ViewportSizeHint(const QsciScintillaBase* self);
void QsciScintillaBase_OnViewportSizeHint(const QsciScintillaBase* self, intptr_t slot);
QSize* QsciScintillaBase_QBaseViewportSizeHint(const QsciScintillaBase* self);
void QsciScintillaBase_InitStyleOption(const QsciScintillaBase* self, QStyleOptionFrame* option);
void QsciScintillaBase_OnInitStyleOption(const QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseInitStyleOption(const QsciScintillaBase* self, QStyleOptionFrame* option);
int QsciScintillaBase_DevType(const QsciScintillaBase* self);
void QsciScintillaBase_OnDevType(const QsciScintillaBase* self, intptr_t slot);
int QsciScintillaBase_QBaseDevType(const QsciScintillaBase* self);
void QsciScintillaBase_SetVisible(QsciScintillaBase* self, bool visible);
void QsciScintillaBase_OnSetVisible(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseSetVisible(QsciScintillaBase* self, bool visible);
int QsciScintillaBase_HeightForWidth(const QsciScintillaBase* self, int param1);
void QsciScintillaBase_OnHeightForWidth(const QsciScintillaBase* self, intptr_t slot);
int QsciScintillaBase_QBaseHeightForWidth(const QsciScintillaBase* self, int param1);
bool QsciScintillaBase_HasHeightForWidth(const QsciScintillaBase* self);
void QsciScintillaBase_OnHasHeightForWidth(const QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseHasHeightForWidth(const QsciScintillaBase* self);
QPaintEngine* QsciScintillaBase_PaintEngine(const QsciScintillaBase* self);
void QsciScintillaBase_OnPaintEngine(const QsciScintillaBase* self, intptr_t slot);
QPaintEngine* QsciScintillaBase_QBasePaintEngine(const QsciScintillaBase* self);
void QsciScintillaBase_KeyReleaseEvent(QsciScintillaBase* self, QKeyEvent* event);
void QsciScintillaBase_OnKeyReleaseEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseKeyReleaseEvent(QsciScintillaBase* self, QKeyEvent* event);
void QsciScintillaBase_EnterEvent(QsciScintillaBase* self, QEnterEvent* event);
void QsciScintillaBase_OnEnterEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseEnterEvent(QsciScintillaBase* self, QEnterEvent* event);
void QsciScintillaBase_LeaveEvent(QsciScintillaBase* self, QEvent* event);
void QsciScintillaBase_OnLeaveEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseLeaveEvent(QsciScintillaBase* self, QEvent* event);
void QsciScintillaBase_MoveEvent(QsciScintillaBase* self, QMoveEvent* event);
void QsciScintillaBase_OnMoveEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseMoveEvent(QsciScintillaBase* self, QMoveEvent* event);
void QsciScintillaBase_CloseEvent(QsciScintillaBase* self, QCloseEvent* event);
void QsciScintillaBase_OnCloseEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseCloseEvent(QsciScintillaBase* self, QCloseEvent* event);
void QsciScintillaBase_TabletEvent(QsciScintillaBase* self, QTabletEvent* event);
void QsciScintillaBase_OnTabletEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseTabletEvent(QsciScintillaBase* self, QTabletEvent* event);
void QsciScintillaBase_ActionEvent(QsciScintillaBase* self, QActionEvent* event);
void QsciScintillaBase_OnActionEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseActionEvent(QsciScintillaBase* self, QActionEvent* event);
void QsciScintillaBase_ShowEvent(QsciScintillaBase* self, QShowEvent* event);
void QsciScintillaBase_OnShowEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseShowEvent(QsciScintillaBase* self, QShowEvent* event);
void QsciScintillaBase_HideEvent(QsciScintillaBase* self, QHideEvent* event);
void QsciScintillaBase_OnHideEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseHideEvent(QsciScintillaBase* self, QHideEvent* event);
bool QsciScintillaBase_NativeEvent(QsciScintillaBase* self, const libqt_string eventType, void* message, intptr_t* result);
void QsciScintillaBase_OnNativeEvent(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseNativeEvent(QsciScintillaBase* self, const libqt_string eventType, void* message, intptr_t* result);
int QsciScintillaBase_Metric(const QsciScintillaBase* self, int param1);
void QsciScintillaBase_OnMetric(const QsciScintillaBase* self, intptr_t slot);
int QsciScintillaBase_QBaseMetric(const QsciScintillaBase* self, int param1);
void QsciScintillaBase_InitPainter(const QsciScintillaBase* self, QPainter* painter);
void QsciScintillaBase_OnInitPainter(const QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseInitPainter(const QsciScintillaBase* self, QPainter* painter);
QPaintDevice* QsciScintillaBase_Redirected(const QsciScintillaBase* self, QPoint* offset);
void QsciScintillaBase_OnRedirected(const QsciScintillaBase* self, intptr_t slot);
QPaintDevice* QsciScintillaBase_QBaseRedirected(const QsciScintillaBase* self, QPoint* offset);
QPainter* QsciScintillaBase_SharedPainter(const QsciScintillaBase* self);
void QsciScintillaBase_OnSharedPainter(const QsciScintillaBase* self, intptr_t slot);
QPainter* QsciScintillaBase_QBaseSharedPainter(const QsciScintillaBase* self);
QVariant* QsciScintillaBase_InputMethodQuery(const QsciScintillaBase* self, int param1);
void QsciScintillaBase_OnInputMethodQuery(const QsciScintillaBase* self, intptr_t slot);
QVariant* QsciScintillaBase_QBaseInputMethodQuery(const QsciScintillaBase* self, int param1);
void QsciScintillaBase_TimerEvent(QsciScintillaBase* self, QTimerEvent* event);
void QsciScintillaBase_OnTimerEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseTimerEvent(QsciScintillaBase* self, QTimerEvent* event);
void QsciScintillaBase_ChildEvent(QsciScintillaBase* self, QChildEvent* event);
void QsciScintillaBase_OnChildEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseChildEvent(QsciScintillaBase* self, QChildEvent* event);
void QsciScintillaBase_CustomEvent(QsciScintillaBase* self, QEvent* event);
void QsciScintillaBase_OnCustomEvent(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseCustomEvent(QsciScintillaBase* self, QEvent* event);
void QsciScintillaBase_ConnectNotify(QsciScintillaBase* self, const QMetaMethod* signal);
void QsciScintillaBase_OnConnectNotify(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseConnectNotify(QsciScintillaBase* self, const QMetaMethod* signal);
void QsciScintillaBase_DisconnectNotify(QsciScintillaBase* self, const QMetaMethod* signal);
void QsciScintillaBase_OnDisconnectNotify(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDisconnectNotify(QsciScintillaBase* self, const QMetaMethod* signal);
void QsciScintillaBase_SetScrollBars(QsciScintillaBase* self);
void QsciScintillaBase_OnSetScrollBars(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseSetScrollBars(QsciScintillaBase* self);
bool QsciScintillaBase_ContextMenuNeeded(const QsciScintillaBase* self, int x, int y);
void QsciScintillaBase_OnContextMenuNeeded(const QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseContextMenuNeeded(const QsciScintillaBase* self, int x, int y);
void QsciScintillaBase_SetViewportMargins(QsciScintillaBase* self, int left, int top, int right, int bottom);
void QsciScintillaBase_OnSetViewportMargins(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseSetViewportMargins(QsciScintillaBase* self, int left, int top, int right, int bottom);
QMargins* QsciScintillaBase_ViewportMargins(const QsciScintillaBase* self);
void QsciScintillaBase_OnViewportMargins(const QsciScintillaBase* self, intptr_t slot);
QMargins* QsciScintillaBase_QBaseViewportMargins(const QsciScintillaBase* self);
void QsciScintillaBase_DrawFrame(QsciScintillaBase* self, QPainter* param1);
void QsciScintillaBase_OnDrawFrame(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDrawFrame(QsciScintillaBase* self, QPainter* param1);
void QsciScintillaBase_UpdateMicroFocus(QsciScintillaBase* self);
void QsciScintillaBase_OnUpdateMicroFocus(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseUpdateMicroFocus(QsciScintillaBase* self);
void QsciScintillaBase_Create(QsciScintillaBase* self);
void QsciScintillaBase_OnCreate(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseCreate(QsciScintillaBase* self);
void QsciScintillaBase_Destroy(QsciScintillaBase* self);
void QsciScintillaBase_OnDestroy(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_QBaseDestroy(QsciScintillaBase* self);
bool QsciScintillaBase_FocusNextChild(QsciScintillaBase* self);
void QsciScintillaBase_OnFocusNextChild(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseFocusNextChild(QsciScintillaBase* self);
bool QsciScintillaBase_FocusPreviousChild(QsciScintillaBase* self);
void QsciScintillaBase_OnFocusPreviousChild(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseFocusPreviousChild(QsciScintillaBase* self);
QObject* QsciScintillaBase_Sender(const QsciScintillaBase* self);
void QsciScintillaBase_OnSender(const QsciScintillaBase* self, intptr_t slot);
QObject* QsciScintillaBase_QBaseSender(const QsciScintillaBase* self);
int QsciScintillaBase_SenderSignalIndex(const QsciScintillaBase* self);
void QsciScintillaBase_OnSenderSignalIndex(const QsciScintillaBase* self, intptr_t slot);
int QsciScintillaBase_QBaseSenderSignalIndex(const QsciScintillaBase* self);
int QsciScintillaBase_Receivers(const QsciScintillaBase* self, const char* signal);
void QsciScintillaBase_OnReceivers(const QsciScintillaBase* self, intptr_t slot);
int QsciScintillaBase_QBaseReceivers(const QsciScintillaBase* self, const char* signal);
bool QsciScintillaBase_IsSignalConnected(const QsciScintillaBase* self, const QMetaMethod* signal);
void QsciScintillaBase_OnIsSignalConnected(const QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_QBaseIsSignalConnected(const QsciScintillaBase* self, const QMetaMethod* signal);
double QsciScintillaBase_GetDecodedMetricF(const QsciScintillaBase* self, int metricA, int metricB);
void QsciScintillaBase_OnGetDecodedMetricF(const QsciScintillaBase* self, intptr_t slot);
double QsciScintillaBase_QBaseGetDecodedMetricF(const QsciScintillaBase* self, int metricA, int metricB);
void QsciScintillaBase_Delete(QsciScintillaBase* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
