#pragma once
#ifndef SRC_EXTRAS_KICONTHEMESC_LIBKICONBUTTON_H
#define SRC_EXTRAS_KICONTHEMESC_LIBKICONBUTTON_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KIconButton KIconButton;
typedef struct QAbstractButton QAbstractButton;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QPushButton QPushButton;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionButton QStyleOptionButton;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KIconButton* KIconButton_new(QWidget* parent);
KIconButton* KIconButton_new2();
QMetaObject* KIconButton_MetaObject(const KIconButton* self);
void* KIconButton_Metacast(KIconButton* self, const char* param1);
int KIconButton_Metacall(KIconButton* self, int param1, int param2, void** param3);
libqt_string KIconButton_Tr(const char* s);
void KIconButton_SetStrictIconSize(KIconButton* self, bool b);
bool KIconButton_StrictIconSize(const KIconButton* self);
void KIconButton_SetIconType(KIconButton* self, int group, int context);
void KIconButton_SetIcon(KIconButton* self, const libqt_string icon);
void KIconButton_SetIcon2(KIconButton* self, const QIcon* icon);
void KIconButton_ResetIcon(KIconButton* self);
libqt_string KIconButton_Icon(const KIconButton* self);
void KIconButton_SetIconSize(KIconButton* self, int size);
int KIconButton_IconSize(const KIconButton* self);
void KIconButton_SetButtonIconSize(KIconButton* self, int size);
int KIconButton_ButtonIconSize(const KIconButton* self);
void KIconButton_IconChanged(KIconButton* self, const libqt_string icon);
void KIconButton_Connect_IconChanged(KIconButton* self, intptr_t slot);
libqt_string KIconButton_Tr2(const char* s, const char* c);
libqt_string KIconButton_Tr3(const char* s, const char* c, int n);
void KIconButton_SetIconType3(KIconButton* self, int group, int context, bool user);
void KIconButton_OnMetacall(KIconButton* self, intptr_t slot);
int KIconButton_QBaseMetacall(KIconButton* self, int param1, int param2, void** param3);
QSize* KIconButton_SizeHint(const KIconButton* self);
void KIconButton_OnSizeHint(const KIconButton* self, intptr_t slot);
QSize* KIconButton_QBaseSizeHint(const KIconButton* self);
QSize* KIconButton_MinimumSizeHint(const KIconButton* self);
void KIconButton_OnMinimumSizeHint(const KIconButton* self, intptr_t slot);
QSize* KIconButton_QBaseMinimumSizeHint(const KIconButton* self);
bool KIconButton_Event(KIconButton* self, QEvent* e);
void KIconButton_OnEvent(KIconButton* self, intptr_t slot);
bool KIconButton_QBaseEvent(KIconButton* self, QEvent* e);
void KIconButton_PaintEvent(KIconButton* self, QPaintEvent* param1);
void KIconButton_OnPaintEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBasePaintEvent(KIconButton* self, QPaintEvent* param1);
void KIconButton_KeyPressEvent(KIconButton* self, QKeyEvent* param1);
void KIconButton_OnKeyPressEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseKeyPressEvent(KIconButton* self, QKeyEvent* param1);
void KIconButton_FocusInEvent(KIconButton* self, QFocusEvent* param1);
void KIconButton_OnFocusInEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseFocusInEvent(KIconButton* self, QFocusEvent* param1);
void KIconButton_FocusOutEvent(KIconButton* self, QFocusEvent* param1);
void KIconButton_OnFocusOutEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseFocusOutEvent(KIconButton* self, QFocusEvent* param1);
void KIconButton_MouseMoveEvent(KIconButton* self, QMouseEvent* param1);
void KIconButton_OnMouseMoveEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseMouseMoveEvent(KIconButton* self, QMouseEvent* param1);
void KIconButton_InitStyleOption(const KIconButton* self, QStyleOptionButton* option);
void KIconButton_OnInitStyleOption(const KIconButton* self, intptr_t slot);
void KIconButton_QBaseInitStyleOption(const KIconButton* self, QStyleOptionButton* option);
bool KIconButton_HitButton(const KIconButton* self, const QPoint* pos);
void KIconButton_OnHitButton(const KIconButton* self, intptr_t slot);
bool KIconButton_QBaseHitButton(const KIconButton* self, const QPoint* pos);
void KIconButton_CheckStateSet(KIconButton* self);
void KIconButton_OnCheckStateSet(KIconButton* self, intptr_t slot);
void KIconButton_QBaseCheckStateSet(KIconButton* self);
void KIconButton_NextCheckState(KIconButton* self);
void KIconButton_OnNextCheckState(KIconButton* self, intptr_t slot);
void KIconButton_QBaseNextCheckState(KIconButton* self);
void KIconButton_KeyReleaseEvent(KIconButton* self, QKeyEvent* e);
void KIconButton_OnKeyReleaseEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseKeyReleaseEvent(KIconButton* self, QKeyEvent* e);
void KIconButton_MousePressEvent(KIconButton* self, QMouseEvent* e);
void KIconButton_OnMousePressEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseMousePressEvent(KIconButton* self, QMouseEvent* e);
void KIconButton_MouseReleaseEvent(KIconButton* self, QMouseEvent* e);
void KIconButton_OnMouseReleaseEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseMouseReleaseEvent(KIconButton* self, QMouseEvent* e);
void KIconButton_ChangeEvent(KIconButton* self, QEvent* e);
void KIconButton_OnChangeEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseChangeEvent(KIconButton* self, QEvent* e);
void KIconButton_TimerEvent(KIconButton* self, QTimerEvent* e);
void KIconButton_OnTimerEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseTimerEvent(KIconButton* self, QTimerEvent* e);
int KIconButton_DevType(const KIconButton* self);
void KIconButton_OnDevType(const KIconButton* self, intptr_t slot);
int KIconButton_QBaseDevType(const KIconButton* self);
void KIconButton_SetVisible(KIconButton* self, bool visible);
void KIconButton_OnSetVisible(KIconButton* self, intptr_t slot);
void KIconButton_QBaseSetVisible(KIconButton* self, bool visible);
int KIconButton_HeightForWidth(const KIconButton* self, int param1);
void KIconButton_OnHeightForWidth(const KIconButton* self, intptr_t slot);
int KIconButton_QBaseHeightForWidth(const KIconButton* self, int param1);
bool KIconButton_HasHeightForWidth(const KIconButton* self);
void KIconButton_OnHasHeightForWidth(const KIconButton* self, intptr_t slot);
bool KIconButton_QBaseHasHeightForWidth(const KIconButton* self);
QPaintEngine* KIconButton_PaintEngine(const KIconButton* self);
void KIconButton_OnPaintEngine(const KIconButton* self, intptr_t slot);
QPaintEngine* KIconButton_QBasePaintEngine(const KIconButton* self);
void KIconButton_MouseDoubleClickEvent(KIconButton* self, QMouseEvent* event);
void KIconButton_OnMouseDoubleClickEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseMouseDoubleClickEvent(KIconButton* self, QMouseEvent* event);
void KIconButton_WheelEvent(KIconButton* self, QWheelEvent* event);
void KIconButton_OnWheelEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseWheelEvent(KIconButton* self, QWheelEvent* event);
void KIconButton_EnterEvent(KIconButton* self, QEnterEvent* event);
void KIconButton_OnEnterEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseEnterEvent(KIconButton* self, QEnterEvent* event);
void KIconButton_LeaveEvent(KIconButton* self, QEvent* event);
void KIconButton_OnLeaveEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseLeaveEvent(KIconButton* self, QEvent* event);
void KIconButton_MoveEvent(KIconButton* self, QMoveEvent* event);
void KIconButton_OnMoveEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseMoveEvent(KIconButton* self, QMoveEvent* event);
void KIconButton_ResizeEvent(KIconButton* self, QResizeEvent* event);
void KIconButton_OnResizeEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseResizeEvent(KIconButton* self, QResizeEvent* event);
void KIconButton_CloseEvent(KIconButton* self, QCloseEvent* event);
void KIconButton_OnCloseEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseCloseEvent(KIconButton* self, QCloseEvent* event);
void KIconButton_ContextMenuEvent(KIconButton* self, QContextMenuEvent* event);
void KIconButton_OnContextMenuEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseContextMenuEvent(KIconButton* self, QContextMenuEvent* event);
void KIconButton_TabletEvent(KIconButton* self, QTabletEvent* event);
void KIconButton_OnTabletEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseTabletEvent(KIconButton* self, QTabletEvent* event);
void KIconButton_ActionEvent(KIconButton* self, QActionEvent* event);
void KIconButton_OnActionEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseActionEvent(KIconButton* self, QActionEvent* event);
void KIconButton_DragEnterEvent(KIconButton* self, QDragEnterEvent* event);
void KIconButton_OnDragEnterEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseDragEnterEvent(KIconButton* self, QDragEnterEvent* event);
void KIconButton_DragMoveEvent(KIconButton* self, QDragMoveEvent* event);
void KIconButton_OnDragMoveEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseDragMoveEvent(KIconButton* self, QDragMoveEvent* event);
void KIconButton_DragLeaveEvent(KIconButton* self, QDragLeaveEvent* event);
void KIconButton_OnDragLeaveEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseDragLeaveEvent(KIconButton* self, QDragLeaveEvent* event);
void KIconButton_DropEvent(KIconButton* self, QDropEvent* event);
void KIconButton_OnDropEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseDropEvent(KIconButton* self, QDropEvent* event);
void KIconButton_ShowEvent(KIconButton* self, QShowEvent* event);
void KIconButton_OnShowEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseShowEvent(KIconButton* self, QShowEvent* event);
void KIconButton_HideEvent(KIconButton* self, QHideEvent* event);
void KIconButton_OnHideEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseHideEvent(KIconButton* self, QHideEvent* event);
bool KIconButton_NativeEvent(KIconButton* self, const libqt_string eventType, void* message, intptr_t* result);
void KIconButton_OnNativeEvent(KIconButton* self, intptr_t slot);
bool KIconButton_QBaseNativeEvent(KIconButton* self, const libqt_string eventType, void* message, intptr_t* result);
int KIconButton_Metric(const KIconButton* self, int param1);
void KIconButton_OnMetric(const KIconButton* self, intptr_t slot);
int KIconButton_QBaseMetric(const KIconButton* self, int param1);
void KIconButton_InitPainter(const KIconButton* self, QPainter* painter);
void KIconButton_OnInitPainter(const KIconButton* self, intptr_t slot);
void KIconButton_QBaseInitPainter(const KIconButton* self, QPainter* painter);
QPaintDevice* KIconButton_Redirected(const KIconButton* self, QPoint* offset);
void KIconButton_OnRedirected(const KIconButton* self, intptr_t slot);
QPaintDevice* KIconButton_QBaseRedirected(const KIconButton* self, QPoint* offset);
QPainter* KIconButton_SharedPainter(const KIconButton* self);
void KIconButton_OnSharedPainter(const KIconButton* self, intptr_t slot);
QPainter* KIconButton_QBaseSharedPainter(const KIconButton* self);
void KIconButton_InputMethodEvent(KIconButton* self, QInputMethodEvent* param1);
void KIconButton_OnInputMethodEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseInputMethodEvent(KIconButton* self, QInputMethodEvent* param1);
QVariant* KIconButton_InputMethodQuery(const KIconButton* self, int param1);
void KIconButton_OnInputMethodQuery(const KIconButton* self, intptr_t slot);
QVariant* KIconButton_QBaseInputMethodQuery(const KIconButton* self, int param1);
bool KIconButton_FocusNextPrevChild(KIconButton* self, bool next);
void KIconButton_OnFocusNextPrevChild(KIconButton* self, intptr_t slot);
bool KIconButton_QBaseFocusNextPrevChild(KIconButton* self, bool next);
bool KIconButton_EventFilter(KIconButton* self, QObject* watched, QEvent* event);
void KIconButton_OnEventFilter(KIconButton* self, intptr_t slot);
bool KIconButton_QBaseEventFilter(KIconButton* self, QObject* watched, QEvent* event);
void KIconButton_ChildEvent(KIconButton* self, QChildEvent* event);
void KIconButton_OnChildEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseChildEvent(KIconButton* self, QChildEvent* event);
void KIconButton_CustomEvent(KIconButton* self, QEvent* event);
void KIconButton_OnCustomEvent(KIconButton* self, intptr_t slot);
void KIconButton_QBaseCustomEvent(KIconButton* self, QEvent* event);
void KIconButton_ConnectNotify(KIconButton* self, const QMetaMethod* signal);
void KIconButton_OnConnectNotify(KIconButton* self, intptr_t slot);
void KIconButton_QBaseConnectNotify(KIconButton* self, const QMetaMethod* signal);
void KIconButton_DisconnectNotify(KIconButton* self, const QMetaMethod* signal);
void KIconButton_OnDisconnectNotify(KIconButton* self, intptr_t slot);
void KIconButton_QBaseDisconnectNotify(KIconButton* self, const QMetaMethod* signal);
void KIconButton_UpdateMicroFocus(KIconButton* self);
void KIconButton_OnUpdateMicroFocus(KIconButton* self, intptr_t slot);
void KIconButton_QBaseUpdateMicroFocus(KIconButton* self);
void KIconButton_Create(KIconButton* self);
void KIconButton_OnCreate(KIconButton* self, intptr_t slot);
void KIconButton_QBaseCreate(KIconButton* self);
void KIconButton_Destroy(KIconButton* self);
void KIconButton_OnDestroy(KIconButton* self, intptr_t slot);
void KIconButton_QBaseDestroy(KIconButton* self);
bool KIconButton_FocusNextChild(KIconButton* self);
void KIconButton_OnFocusNextChild(KIconButton* self, intptr_t slot);
bool KIconButton_QBaseFocusNextChild(KIconButton* self);
bool KIconButton_FocusPreviousChild(KIconButton* self);
void KIconButton_OnFocusPreviousChild(KIconButton* self, intptr_t slot);
bool KIconButton_QBaseFocusPreviousChild(KIconButton* self);
QObject* KIconButton_Sender(const KIconButton* self);
void KIconButton_OnSender(const KIconButton* self, intptr_t slot);
QObject* KIconButton_QBaseSender(const KIconButton* self);
int KIconButton_SenderSignalIndex(const KIconButton* self);
void KIconButton_OnSenderSignalIndex(const KIconButton* self, intptr_t slot);
int KIconButton_QBaseSenderSignalIndex(const KIconButton* self);
int KIconButton_Receivers(const KIconButton* self, const char* signal);
void KIconButton_OnReceivers(const KIconButton* self, intptr_t slot);
int KIconButton_QBaseReceivers(const KIconButton* self, const char* signal);
bool KIconButton_IsSignalConnected(const KIconButton* self, const QMetaMethod* signal);
void KIconButton_OnIsSignalConnected(const KIconButton* self, intptr_t slot);
bool KIconButton_QBaseIsSignalConnected(const KIconButton* self, const QMetaMethod* signal);
double KIconButton_GetDecodedMetricF(const KIconButton* self, int metricA, int metricB);
void KIconButton_OnGetDecodedMetricF(const KIconButton* self, intptr_t slot);
double KIconButton_QBaseGetDecodedMetricF(const KIconButton* self, int metricA, int metricB);
void KIconButton_Delete(KIconButton* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
